/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nyu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AnswerRequest service. Represents a row in the &quot;nyyou_AnswerRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nyu.model.impl.AnswerRequestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nyu.model.impl.AnswerRequestImpl}.
 * </p>
 *
 * @author Allwins Rajaiah
 * @see AnswerRequest
 * @see com.nyu.model.impl.AnswerRequestImpl
 * @see com.nyu.model.impl.AnswerRequestModelImpl
 * @generated
 */
public interface AnswerRequestModel extends BaseModel<AnswerRequest> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a answer request model instance should use the {@link AnswerRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this answer request.
	 *
	 * @return the primary key of this answer request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this answer request.
	 *
	 * @param primaryKey the primary key of this answer request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the answer ID of this answer request.
	 *
	 * @return the answer ID of this answer request
	 */
	public long getAnswerId();

	/**
	 * Sets the answer ID of this answer request.
	 *
	 * @param answerId the answer ID of this answer request
	 */
	public void setAnswerId(long answerId);

	/**
	 * Returns the request lesson ID of this answer request.
	 *
	 * @return the request lesson ID of this answer request
	 */
	public long getRequestLessonId();

	/**
	 * Sets the request lesson ID of this answer request.
	 *
	 * @param requestLessonId the request lesson ID of this answer request
	 */
	public void setRequestLessonId(long requestLessonId);

	/**
	 * Returns the user ID of this answer request.
	 *
	 * @return the user ID of this answer request
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this answer request.
	 *
	 * @param userId the user ID of this answer request
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this answer request.
	 *
	 * @return the user uuid of this answer request
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this answer request.
	 *
	 * @param userUuid the user uuid of this answer request
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the description of this answer request.
	 *
	 * @return the description of this answer request
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this answer request.
	 *
	 * @param description the description of this answer request
	 */
	public void setDescription(String description);

	/**
	 * Returns the appreciate user IDs of this answer request.
	 *
	 * @return the appreciate user IDs of this answer request
	 */
	@AutoEscape
	public String getAppreciateUserIds();

	/**
	 * Sets the appreciate user IDs of this answer request.
	 *
	 * @param appreciateUserIds the appreciate user IDs of this answer request
	 */
	public void setAppreciateUserIds(String appreciateUserIds);

	/**
	 * Returns the appreciate count of this answer request.
	 *
	 * @return the appreciate count of this answer request
	 */
	public int getAppreciateCount();

	/**
	 * Sets the appreciate count of this answer request.
	 *
	 * @param appreciateCount the appreciate count of this answer request
	 */
	public void setAppreciateCount(int appreciateCount);

	/**
	 * Returns the create date of this answer request.
	 *
	 * @return the create date of this answer request
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this answer request.
	 *
	 * @param createDate the create date of this answer request
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the checked answer of this answer request.
	 *
	 * @return the checked answer of this answer request
	 */
	public boolean getCheckedAnswer();

	/**
	 * Returns <code>true</code> if this answer request is checked answer.
	 *
	 * @return <code>true</code> if this answer request is checked answer; <code>false</code> otherwise
	 */
	public boolean isCheckedAnswer();

	/**
	 * Sets whether this answer request is checked answer.
	 *
	 * @param checkedAnswer the checked answer of this answer request
	 */
	public void setCheckedAnswer(boolean checkedAnswer);

	/**
	 * Returns the opinion survey of this answer request.
	 *
	 * @return the opinion survey of this answer request
	 */
	@AutoEscape
	public String getOpinionSurvey();

	/**
	 * Sets the opinion survey of this answer request.
	 *
	 * @param opinionSurvey the opinion survey of this answer request
	 */
	public void setOpinionSurvey(String opinionSurvey);

	/**
	 * Returns the my lessons of this answer request.
	 *
	 * @return the my lessons of this answer request
	 */
	@AutoEscape
	public String getMyLessons();

	/**
	 * Sets the my lessons of this answer request.
	 *
	 * @param myLessons the my lessons of this answer request
	 */
	public void setMyLessons(String myLessons);

	/**
	 * Returns the my favourite lessons of this answer request.
	 *
	 * @return the my favourite lessons of this answer request
	 */
	@AutoEscape
	public String getMyFavouriteLessons();

	/**
	 * Sets the my favourite lessons of this answer request.
	 *
	 * @param myFavouriteLessons the my favourite lessons of this answer request
	 */
	public void setMyFavouriteLessons(String myFavouriteLessons);

	/**
	 * Returns the collaboration lessons of this answer request.
	 *
	 * @return the collaboration lessons of this answer request
	 */
	public long getCollaborationLessons();

	/**
	 * Sets the collaboration lessons of this answer request.
	 *
	 * @param collaborationLessons the collaboration lessons of this answer request
	 */
	public void setCollaborationLessons(long collaborationLessons);

	/**
	 * Returns the collaboration ID of this answer request.
	 *
	 * @return the collaboration ID of this answer request
	 */
	public long getCollaborationId();

	/**
	 * Sets the collaboration ID of this answer request.
	 *
	 * @param collaborationId the collaboration ID of this answer request
	 */
	public void setCollaborationId(long collaborationId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AnswerRequest answerRequest);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AnswerRequest> toCacheModel();

	@Override
	public AnswerRequest toEscapedModel();

	@Override
	public AnswerRequest toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}