/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nyu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AuditReport service. Represents a row in the &quot;nyyou_AuditReport&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nyu.model.impl.AuditReportModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nyu.model.impl.AuditReportImpl}.
 * </p>
 *
 * @author Allwins Rajaiah
 * @see AuditReport
 * @see com.nyu.model.impl.AuditReportImpl
 * @see com.nyu.model.impl.AuditReportModelImpl
 * @generated
 */
public interface AuditReportModel extends BaseModel<AuditReport> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a audit report model instance should use the {@link AuditReport} interface instead.
	 */

	/**
	 * Returns the primary key of this audit report.
	 *
	 * @return the primary key of this audit report
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this audit report.
	 *
	 * @param primaryKey the primary key of this audit report
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the audit event ID of this audit report.
	 *
	 * @return the audit event ID of this audit report
	 */
	public long getAuditEventId();

	/**
	 * Sets the audit event ID of this audit report.
	 *
	 * @param auditEventId the audit event ID of this audit report
	 */
	public void setAuditEventId(long auditEventId);

	/**
	 * Returns the company ID of this audit report.
	 *
	 * @return the company ID of this audit report
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this audit report.
	 *
	 * @param companyId the company ID of this audit report
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this audit report.
	 *
	 * @return the group ID of this audit report
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this audit report.
	 *
	 * @param groupId the group ID of this audit report
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this audit report.
	 *
	 * @return the user ID of this audit report
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this audit report.
	 *
	 * @param userId the user ID of this audit report
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this audit report.
	 *
	 * @return the user uuid of this audit report
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this audit report.
	 *
	 * @param userUuid the user uuid of this audit report
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this audit report.
	 *
	 * @return the user name of this audit report
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this audit report.
	 *
	 * @param userName the user name of this audit report
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this audit report.
	 *
	 * @return the create date of this audit report
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this audit report.
	 *
	 * @param createDate the create date of this audit report
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the event type of this audit report.
	 *
	 * @return the event type of this audit report
	 */
	@AutoEscape
	public String getEventType();

	/**
	 * Sets the event type of this audit report.
	 *
	 * @param eventType the event type of this audit report
	 */
	public void setEventType(String eventType);

	/**
	 * Returns the class name of this audit report.
	 *
	 * @return the class name of this audit report
	 */
	@AutoEscape
	public String getClassName();

	/**
	 * Sets the class name of this audit report.
	 *
	 * @param className the class name of this audit report
	 */
	public void setClassName(String className);

	/**
	 * Returns the class p k of this audit report.
	 *
	 * @return the class p k of this audit report
	 */
	@AutoEscape
	public String getClassPK();

	/**
	 * Sets the class p k of this audit report.
	 *
	 * @param classPK the class p k of this audit report
	 */
	public void setClassPK(String classPK);

	/**
	 * Returns the message of this audit report.
	 *
	 * @return the message of this audit report
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this audit report.
	 *
	 * @param message the message of this audit report
	 */
	public void setMessage(String message);

	/**
	 * Returns the client host of this audit report.
	 *
	 * @return the client host of this audit report
	 */
	@AutoEscape
	public String getClientHost();

	/**
	 * Sets the client host of this audit report.
	 *
	 * @param clientHost the client host of this audit report
	 */
	public void setClientHost(String clientHost);

	/**
	 * Returns the client i p of this audit report.
	 *
	 * @return the client i p of this audit report
	 */
	@AutoEscape
	public String getClientIP();

	/**
	 * Sets the client i p of this audit report.
	 *
	 * @param clientIP the client i p of this audit report
	 */
	public void setClientIP(String clientIP);

	/**
	 * Returns the server name of this audit report.
	 *
	 * @return the server name of this audit report
	 */
	@AutoEscape
	public String getServerName();

	/**
	 * Sets the server name of this audit report.
	 *
	 * @param serverName the server name of this audit report
	 */
	public void setServerName(String serverName);

	/**
	 * Returns the server port of this audit report.
	 *
	 * @return the server port of this audit report
	 */
	public int getServerPort();

	/**
	 * Sets the server port of this audit report.
	 *
	 * @param serverPort the server port of this audit report
	 */
	public void setServerPort(int serverPort);

	/**
	 * Returns the session i d of this audit report.
	 *
	 * @return the session i d of this audit report
	 */
	@AutoEscape
	public String getSessionID();

	/**
	 * Sets the session i d of this audit report.
	 *
	 * @param sessionID the session i d of this audit report
	 */
	public void setSessionID(String sessionID);

	/**
	 * Returns the additional info of this audit report.
	 *
	 * @return the additional info of this audit report
	 */
	@AutoEscape
	public String getAdditionalInfo();

	/**
	 * Sets the additional info of this audit report.
	 *
	 * @param additionalInfo the additional info of this audit report
	 */
	public void setAdditionalInfo(String additionalInfo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AuditReport auditReport);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AuditReport> toCacheModel();

	@Override
	public AuditReport toEscapedModel();

	@Override
	public AuditReport toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}