/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nyu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Basno service. Represents a row in the &quot;nyyou_Basno&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nyu.model.impl.BasnoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nyu.model.impl.BasnoImpl}.
 * </p>
 *
 * @author Allwins Rajaiah
 * @see Basno
 * @see com.nyu.model.impl.BasnoImpl
 * @see com.nyu.model.impl.BasnoModelImpl
 * @generated
 */
public interface BasnoModel extends BaseModel<Basno> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a basno model instance should use the {@link Basno} interface instead.
	 */

	/**
	 * Returns the primary key of this basno.
	 *
	 * @return the primary key of this basno
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this basno.
	 *
	 * @param primaryKey the primary key of this basno
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the badge ID of this basno.
	 *
	 * @return the badge ID of this basno
	 */
	public long getBadgeId();

	/**
	 * Sets the badge ID of this basno.
	 *
	 * @param badgeId the badge ID of this basno
	 */
	public void setBadgeId(long badgeId);

	/**
	 * Returns the company ID of this basno.
	 *
	 * @return the company ID of this basno
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this basno.
	 *
	 * @param companyId the company ID of this basno
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this basno.
	 *
	 * @return the group ID of this basno
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this basno.
	 *
	 * @param groupId the group ID of this basno
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the badge name of this basno.
	 *
	 * @return the badge name of this basno
	 */
	@AutoEscape
	public String getBadgeName();

	/**
	 * Sets the badge name of this basno.
	 *
	 * @param badgeName the badge name of this basno
	 */
	public void setBadgeName(String badgeName);

	/**
	 * Returns the badge url of this basno.
	 *
	 * @return the badge url of this basno
	 */
	@AutoEscape
	public String getBadgeUrl();

	/**
	 * Sets the badge url of this basno.
	 *
	 * @param badgeUrl the badge url of this basno
	 */
	public void setBadgeUrl(String badgeUrl);

	/**
	 * Returns the description of this basno.
	 *
	 * @return the description of this basno
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this basno.
	 *
	 * @param description the description of this basno
	 */
	public void setDescription(String description);

	/**
	 * Returns the target points of this basno.
	 *
	 * @return the target points of this basno
	 */
	public long getTargetPoints();

	/**
	 * Sets the target points of this basno.
	 *
	 * @param targetPoints the target points of this basno
	 */
	public void setTargetPoints(long targetPoints);

	/**
	 * Returns the created date of this basno.
	 *
	 * @return the created date of this basno
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this basno.
	 *
	 * @param createdDate the created date of this basno
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the created by of this basno.
	 *
	 * @return the created by of this basno
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this basno.
	 *
	 * @param createdBy the created by of this basno
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the updated date of this basno.
	 *
	 * @return the updated date of this basno
	 */
	public Date getUpdatedDate();

	/**
	 * Sets the updated date of this basno.
	 *
	 * @param updatedDate the updated date of this basno
	 */
	public void setUpdatedDate(Date updatedDate);

	/**
	 * Returns the updated by of this basno.
	 *
	 * @return the updated by of this basno
	 */
	public long getUpdatedBy();

	/**
	 * Sets the updated by of this basno.
	 *
	 * @param updatedBy the updated by of this basno
	 */
	public void setUpdatedBy(long updatedBy);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Basno basno);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Basno> toCacheModel();

	@Override
	public Basno toEscapedModel();

	@Override
	public Basno toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}