/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nyu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the DocumentSection service. Represents a row in the &quot;nyyou_DocumentSection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nyu.model.impl.DocumentSectionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nyu.model.impl.DocumentSectionImpl}.
 * </p>
 *
 * @author Allwins Rajaiah
 * @see DocumentSection
 * @see com.nyu.model.impl.DocumentSectionImpl
 * @see com.nyu.model.impl.DocumentSectionModelImpl
 * @generated
 */
public interface DocumentSectionModel extends BaseModel<DocumentSection> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document section model instance should use the {@link DocumentSection} interface instead.
	 */

	/**
	 * Returns the primary key of this document section.
	 *
	 * @return the primary key of this document section
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document section.
	 *
	 * @param primaryKey the primary key of this document section
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this document section.
	 *
	 * @return the ID of this document section
	 */
	public long getId();

	/**
	 * Sets the ID of this document section.
	 *
	 * @param id the ID of this document section
	 */
	public void setId(long id);

	/**
	 * Returns the lesson ID of this document section.
	 *
	 * @return the lesson ID of this document section
	 */
	public long getLessonId();

	/**
	 * Sets the lesson ID of this document section.
	 *
	 * @param lessonId the lesson ID of this document section
	 */
	public void setLessonId(long lessonId);

	/**
	 * Returns the document ID of this document section.
	 *
	 * @return the document ID of this document section
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this document section.
	 *
	 * @param documentId the document ID of this document section
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the modified date of this document section.
	 *
	 * @return the modified date of this document section
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this document section.
	 *
	 * @param modifiedDate the modified date of this document section
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the section title of this document section.
	 *
	 * @return the section title of this document section
	 */
	@AutoEscape
	public String getSectionTitle();

	/**
	 * Sets the section title of this document section.
	 *
	 * @param sectionTitle the section title of this document section
	 */
	public void setSectionTitle(String sectionTitle);

	/**
	 * Returns the section note of this document section.
	 *
	 * @return the section note of this document section
	 */
	@AutoEscape
	public String getSectionNote();

	/**
	 * Sets the section note of this document section.
	 *
	 * @param sectionNote the section note of this document section
	 */
	public void setSectionNote(String sectionNote);

	/**
	 * Returns the lesson objective IDs of this document section.
	 *
	 * @return the lesson objective IDs of this document section
	 */
	@AutoEscape
	public String getLessonObjectiveIds();

	/**
	 * Sets the lesson objective IDs of this document section.
	 *
	 * @param lessonObjectiveIds the lesson objective IDs of this document section
	 */
	public void setLessonObjectiveIds(String lessonObjectiveIds);

	/**
	 * Returns the order of this document section.
	 *
	 * @return the order of this document section
	 */
	public int getOrder();

	/**
	 * Sets the order of this document section.
	 *
	 * @param order the order of this document section
	 */
	public void setOrder(int order);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(DocumentSection documentSection);

	@Override
	public int hashCode();

	@Override
	public CacheModel<DocumentSection> toCacheModel();

	@Override
	public DocumentSection toEscapedModel();

	@Override
	public DocumentSection toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}