/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nyu.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.nyu.service.persistence.FavouriteLessonsPK;

import java.io.Serializable;

/**
 * The base model interface for the FavouriteLessons service. Represents a row in the &quot;nyyou_FavouriteLessons&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nyu.model.impl.FavouriteLessonsModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nyu.model.impl.FavouriteLessonsImpl}.
 * </p>
 *
 * @author Allwins Rajaiah
 * @see FavouriteLessons
 * @see com.nyu.model.impl.FavouriteLessonsImpl
 * @see com.nyu.model.impl.FavouriteLessonsModelImpl
 * @generated
 */
public interface FavouriteLessonsModel extends BaseModel<FavouriteLessons> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a favourite lessons model instance should use the {@link FavouriteLessons} interface instead.
	 */

	/**
	 * Returns the primary key of this favourite lessons.
	 *
	 * @return the primary key of this favourite lessons
	 */
	public FavouriteLessonsPK getPrimaryKey();

	/**
	 * Sets the primary key of this favourite lessons.
	 *
	 * @param primaryKey the primary key of this favourite lessons
	 */
	public void setPrimaryKey(FavouriteLessonsPK primaryKey);

	/**
	 * Returns the user ID of this favourite lessons.
	 *
	 * @return the user ID of this favourite lessons
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this favourite lessons.
	 *
	 * @param userId the user ID of this favourite lessons
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this favourite lessons.
	 *
	 * @return the user uuid of this favourite lessons
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this favourite lessons.
	 *
	 * @param userUuid the user uuid of this favourite lessons
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the lesson ID of this favourite lessons.
	 *
	 * @return the lesson ID of this favourite lessons
	 */
	public long getLessonId();

	/**
	 * Sets the lesson ID of this favourite lessons.
	 *
	 * @param lessonId the lesson ID of this favourite lessons
	 */
	public void setLessonId(long lessonId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FavouriteLessons favouriteLessons);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FavouriteLessons> toCacheModel();

	@Override
	public FavouriteLessons toEscapedModel();

	@Override
	public FavouriteLessons toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}