/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nyu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the KeywordsCollaboration service. Represents a row in the &quot;nyyou_KeywordsCollaboration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nyu.model.impl.KeywordsCollaborationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nyu.model.impl.KeywordsCollaborationImpl}.
 * </p>
 *
 * @author Allwins Rajaiah
 * @see KeywordsCollaboration
 * @see com.nyu.model.impl.KeywordsCollaborationImpl
 * @see com.nyu.model.impl.KeywordsCollaborationModelImpl
 * @generated
 */
public interface KeywordsCollaborationModel extends BaseModel<KeywordsCollaboration> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a keywords collaboration model instance should use the {@link KeywordsCollaboration} interface instead.
	 */

	/**
	 * Returns the primary key of this keywords collaboration.
	 *
	 * @return the primary key of this keywords collaboration
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this keywords collaboration.
	 *
	 * @param primaryKey the primary key of this keywords collaboration
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this keywords collaboration.
	 *
	 * @return the ID of this keywords collaboration
	 */
	public long getId();

	/**
	 * Sets the ID of this keywords collaboration.
	 *
	 * @param id the ID of this keywords collaboration
	 */
	public void setId(long id);

	/**
	 * Returns the company ID of this keywords collaboration.
	 *
	 * @return the company ID of this keywords collaboration
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this keywords collaboration.
	 *
	 * @param companyId the company ID of this keywords collaboration
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this keywords collaboration.
	 *
	 * @return the group ID of this keywords collaboration
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this keywords collaboration.
	 *
	 * @param groupId the group ID of this keywords collaboration
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the keyword ID of this keywords collaboration.
	 *
	 * @return the keyword ID of this keywords collaboration
	 */
	public long getKeywordId();

	/**
	 * Sets the keyword ID of this keywords collaboration.
	 *
	 * @param keywordId the keyword ID of this keywords collaboration
	 */
	public void setKeywordId(long keywordId);

	/**
	 * Returns the keyword name of this keywords collaboration.
	 *
	 * @return the keyword name of this keywords collaboration
	 */
	@AutoEscape
	public String getKeywordName();

	/**
	 * Sets the keyword name of this keywords collaboration.
	 *
	 * @param keywordName the keyword name of this keywords collaboration
	 */
	public void setKeywordName(String keywordName);

	/**
	 * Returns the user ID of this keywords collaboration.
	 *
	 * @return the user ID of this keywords collaboration
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this keywords collaboration.
	 *
	 * @param userId the user ID of this keywords collaboration
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this keywords collaboration.
	 *
	 * @return the user uuid of this keywords collaboration
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this keywords collaboration.
	 *
	 * @param userUuid the user uuid of this keywords collaboration
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this keywords collaboration.
	 *
	 * @return the user name of this keywords collaboration
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this keywords collaboration.
	 *
	 * @param userName the user name of this keywords collaboration
	 */
	public void setUserName(String userName);

	/**
	 * Returns the status of this keywords collaboration.
	 *
	 * @return the status of this keywords collaboration
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this keywords collaboration.
	 *
	 * @param status the status of this keywords collaboration
	 */
	public void setStatus(String status);

	/**
	 * Returns the created date of this keywords collaboration.
	 *
	 * @return the created date of this keywords collaboration
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this keywords collaboration.
	 *
	 * @param createdDate the created date of this keywords collaboration
	 */
	public void setCreatedDate(Date createdDate);

	/**
	 * Returns the modified date of this keywords collaboration.
	 *
	 * @return the modified date of this keywords collaboration
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this keywords collaboration.
	 *
	 * @param modifiedDate the modified date of this keywords collaboration
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the mark as of this keywords collaboration.
	 *
	 * @return the mark as of this keywords collaboration
	 */
	@AutoEscape
	public String getMarkAs();

	/**
	 * Sets the mark as of this keywords collaboration.
	 *
	 * @param markAs the mark as of this keywords collaboration
	 */
	public void setMarkAs(String markAs);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(KeywordsCollaboration keywordsCollaboration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<KeywordsCollaboration> toCacheModel();

	@Override
	public KeywordsCollaboration toEscapedModel();

	@Override
	public KeywordsCollaboration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}