/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nyu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserGroupRequest service. Represents a row in the &quot;nyyou_UserGroupRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nyu.model.impl.UserGroupRequestModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nyu.model.impl.UserGroupRequestImpl}.
 * </p>
 *
 * @author Allwins Rajaiah
 * @see UserGroupRequest
 * @see com.nyu.model.impl.UserGroupRequestImpl
 * @see com.nyu.model.impl.UserGroupRequestModelImpl
 * @generated
 */
public interface UserGroupRequestModel extends BaseModel<UserGroupRequest> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user group request model instance should use the {@link UserGroupRequest} interface instead.
	 */

	/**
	 * Returns the primary key of this user group request.
	 *
	 * @return the primary key of this user group request
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user group request.
	 *
	 * @param primaryKey the primary key of this user group request
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this user group request.
	 *
	 * @return the ID of this user group request
	 */
	public long getId();

	/**
	 * Sets the ID of this user group request.
	 *
	 * @param id the ID of this user group request
	 */
	public void setId(long id);

	/**
	 * Returns the user group ID of this user group request.
	 *
	 * @return the user group ID of this user group request
	 */
	public long getUserGroupId();

	/**
	 * Sets the user group ID of this user group request.
	 *
	 * @param userGroupId the user group ID of this user group request
	 */
	public void setUserGroupId(long userGroupId);

	/**
	 * Returns the company ID of this user group request.
	 *
	 * @return the company ID of this user group request
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this user group request.
	 *
	 * @param companyId the company ID of this user group request
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this user group request.
	 *
	 * @return the group ID of this user group request
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this user group request.
	 *
	 * @param groupId the group ID of this user group request
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user group owner of this user group request.
	 *
	 * @return the user group owner of this user group request
	 */
	public long getUserGroupOwner();

	/**
	 * Sets the user group owner of this user group request.
	 *
	 * @param userGroupOwner the user group owner of this user group request
	 */
	public void setUserGroupOwner(long userGroupOwner);

	/**
	 * Returns the request date of this user group request.
	 *
	 * @return the request date of this user group request
	 */
	public Date getRequestDate();

	/**
	 * Sets the request date of this user group request.
	 *
	 * @param requestDate the request date of this user group request
	 */
	public void setRequestDate(Date requestDate);

	/**
	 * Returns the requested by of this user group request.
	 *
	 * @return the requested by of this user group request
	 */
	public long getRequestedBy();

	/**
	 * Sets the requested by of this user group request.
	 *
	 * @param requestedBy the requested by of this user group request
	 */
	public void setRequestedBy(long requestedBy);

	/**
	 * Returns the status of this user group request.
	 *
	 * @return the status of this user group request
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this user group request.
	 *
	 * @param status the status of this user group request
	 */
	public void setStatus(String status);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserGroupRequest userGroupRequest);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserGroupRequest> toCacheModel();

	@Override
	public UserGroupRequest toEscapedModel();

	@Override
	public UserGroupRequest toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}