/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nyu.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the UserBadges service. Represents a row in the &quot;nyyou_UserBadges&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.nyu.model.impl.UserBadgesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.nyu.model.impl.UserBadgesImpl}.
 * </p>
 *
 * @author Allwins Rajaiah
 * @see UserBadges
 * @see com.nyu.model.impl.UserBadgesImpl
 * @see com.nyu.model.impl.UserBadgesModelImpl
 * @generated
 */
public interface UserBadgesModel extends BaseModel<UserBadges> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user badges model instance should use the {@link UserBadges} interface instead.
	 */

	/**
	 * Returns the primary key of this user badges.
	 *
	 * @return the primary key of this user badges
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user badges.
	 *
	 * @param primaryKey the primary key of this user badges
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user badge ID of this user badges.
	 *
	 * @return the user badge ID of this user badges
	 */
	public long getUserBadgeId();

	/**
	 * Sets the user badge ID of this user badges.
	 *
	 * @param userBadgeId the user badge ID of this user badges
	 */
	public void setUserBadgeId(long userBadgeId);

	/**
	 * Returns the user ID of this user badges.
	 *
	 * @return the user ID of this user badges
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this user badges.
	 *
	 * @param userId the user ID of this user badges
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user badges.
	 *
	 * @return the user uuid of this user badges
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this user badges.
	 *
	 * @param userUuid the user uuid of this user badges
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the badge ID of this user badges.
	 *
	 * @return the badge ID of this user badges
	 */
	public long getBadgeId();

	/**
	 * Sets the badge ID of this user badges.
	 *
	 * @param badgeId the badge ID of this user badges
	 */
	public void setBadgeId(long badgeId);

	/**
	 * Returns the badge url of this user badges.
	 *
	 * @return the badge url of this user badges
	 */
	@AutoEscape
	public String getBadgeUrl();

	/**
	 * Sets the badge url of this user badges.
	 *
	 * @param badgeUrl the badge url of this user badges
	 */
	public void setBadgeUrl(String badgeUrl);

	/**
	 * Returns the created date of this user badges.
	 *
	 * @return the created date of this user badges
	 */
	public Date getCreatedDate();

	/**
	 * Sets the created date of this user badges.
	 *
	 * @param createdDate the created date of this user badges
	 */
	public void setCreatedDate(Date createdDate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(UserBadges userBadges);

	@Override
	public int hashCode();

	@Override
	public CacheModel<UserBadges> toCacheModel();

	@Override
	public UserBadges toEscapedModel();

	@Override
	public UserBadges toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}