/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.nyu.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.nyu.model.Slides;
import com.nyu.model.SlidesModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Slides service. Represents a row in the &quot;nyyou_Slides&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.nyu.model.SlidesModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SlidesImpl}.
 * </p>
 *
 * @author Allwins Rajaiah
 * @see SlidesImpl
 * @see com.nyu.model.Slides
 * @see com.nyu.model.SlidesModel
 * @generated
 */
public class SlidesModelImpl extends BaseModelImpl<Slides>
	implements SlidesModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a slides model instance should use the {@link com.nyu.model.Slides} interface instead.
	 */
	public static final String TABLE_NAME = "nyyou_Slides";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "description", Types.VARCHAR },
			{ "descPosition", Types.VARCHAR },
			{ "imageLink", Types.VARCHAR },
			{ "createdDate", Types.TIMESTAMP },
			{ "createdBy", Types.BIGINT },
			{ "updatedDate", Types.TIMESTAMP },
			{ "updatedBy", Types.BIGINT }
		};
	public static final String TABLE_SQL_CREATE = "create table nyyou_Slides (id_ LONG not null primary key IDENTITY,description TEXT null,descPosition VARCHAR(75) null,imageLink VARCHAR(75) null,createdDate DATE null,createdBy LONG,updatedDate DATE null,updatedBy LONG)";
	public static final String TABLE_SQL_DROP = "drop table nyyou_Slides";
	public static final String ORDER_BY_JPQL = " ORDER BY slides.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY nyyou_Slides.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.nyu.model.Slides"), true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.nyu.model.Slides"), true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.nyu.model.Slides"),
			true);
	public static long ID_COLUMN_BITMASK = 1L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.nyu.model.Slides"));

	public SlidesModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Slides.class;
	}

	@Override
	public String getModelClassName() {
		return Slides.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("description", getDescription());
		attributes.put("descPosition", getDescPosition());
		attributes.put("imageLink", getImageLink());
		attributes.put("createdDate", getCreatedDate());
		attributes.put("createdBy", getCreatedBy());
		attributes.put("updatedDate", getUpdatedDate());
		attributes.put("updatedBy", getUpdatedBy());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String description = (String)attributes.get("description");

		if (description != null) {
			setDescription(description);
		}

		String descPosition = (String)attributes.get("descPosition");

		if (descPosition != null) {
			setDescPosition(descPosition);
		}

		String imageLink = (String)attributes.get("imageLink");

		if (imageLink != null) {
			setImageLink(imageLink);
		}

		Date createdDate = (Date)attributes.get("createdDate");

		if (createdDate != null) {
			setCreatedDate(createdDate);
		}

		Long createdBy = (Long)attributes.get("createdBy");

		if (createdBy != null) {
			setCreatedBy(createdBy);
		}

		Date updatedDate = (Date)attributes.get("updatedDate");

		if (updatedDate != null) {
			setUpdatedDate(updatedDate);
		}

		Long updatedBy = (Long)attributes.get("updatedBy");

		if (updatedBy != null) {
			setUpdatedBy(updatedBy);
		}
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask |= ID_COLUMN_BITMASK;

		if (!_setOriginalId) {
			_setOriginalId = true;

			_originalId = _id;
		}

		_id = id;
	}

	public long getOriginalId() {
		return _originalId;
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return StringPool.BLANK;
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public String getDescPosition() {
		if (_descPosition == null) {
			return StringPool.BLANK;
		}
		else {
			return _descPosition;
		}
	}

	@Override
	public void setDescPosition(String descPosition) {
		_descPosition = descPosition;
	}

	@Override
	public String getImageLink() {
		if (_imageLink == null) {
			return StringPool.BLANK;
		}
		else {
			return _imageLink;
		}
	}

	@Override
	public void setImageLink(String imageLink) {
		_imageLink = imageLink;
	}

	@Override
	public Date getCreatedDate() {
		return _createdDate;
	}

	@Override
	public void setCreatedDate(Date createdDate) {
		_createdDate = createdDate;
	}

	@Override
	public long getCreatedBy() {
		return _createdBy;
	}

	@Override
	public void setCreatedBy(long createdBy) {
		_createdBy = createdBy;
	}

	@Override
	public Date getUpdatedDate() {
		return _updatedDate;
	}

	@Override
	public void setUpdatedDate(Date updatedDate) {
		_updatedDate = updatedDate;
	}

	@Override
	public long getUpdatedBy() {
		return _updatedBy;
	}

	@Override
	public void setUpdatedBy(long updatedBy) {
		_updatedBy = updatedBy;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Slides.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Slides toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Slides)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SlidesImpl slidesImpl = new SlidesImpl();

		slidesImpl.setId(getId());
		slidesImpl.setDescription(getDescription());
		slidesImpl.setDescPosition(getDescPosition());
		slidesImpl.setImageLink(getImageLink());
		slidesImpl.setCreatedDate(getCreatedDate());
		slidesImpl.setCreatedBy(getCreatedBy());
		slidesImpl.setUpdatedDate(getUpdatedDate());
		slidesImpl.setUpdatedBy(getUpdatedBy());

		slidesImpl.resetOriginalValues();

		return slidesImpl;
	}

	@Override
	public int compareTo(Slides slides) {
		long primaryKey = slides.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Slides)) {
			return false;
		}

		Slides slides = (Slides)obj;

		long primaryKey = slides.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		SlidesModelImpl slidesModelImpl = this;

		slidesModelImpl._originalId = slidesModelImpl._id;

		slidesModelImpl._setOriginalId = false;

		slidesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Slides> toCacheModel() {
		SlidesCacheModel slidesCacheModel = new SlidesCacheModel();

		slidesCacheModel.id = getId();

		slidesCacheModel.description = getDescription();

		String description = slidesCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			slidesCacheModel.description = null;
		}

		slidesCacheModel.descPosition = getDescPosition();

		String descPosition = slidesCacheModel.descPosition;

		if ((descPosition != null) && (descPosition.length() == 0)) {
			slidesCacheModel.descPosition = null;
		}

		slidesCacheModel.imageLink = getImageLink();

		String imageLink = slidesCacheModel.imageLink;

		if ((imageLink != null) && (imageLink.length() == 0)) {
			slidesCacheModel.imageLink = null;
		}

		Date createdDate = getCreatedDate();

		if (createdDate != null) {
			slidesCacheModel.createdDate = createdDate.getTime();
		}
		else {
			slidesCacheModel.createdDate = Long.MIN_VALUE;
		}

		slidesCacheModel.createdBy = getCreatedBy();

		Date updatedDate = getUpdatedDate();

		if (updatedDate != null) {
			slidesCacheModel.updatedDate = updatedDate.getTime();
		}
		else {
			slidesCacheModel.updatedDate = Long.MIN_VALUE;
		}

		slidesCacheModel.updatedBy = getUpdatedBy();

		return slidesCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", description=");
		sb.append(getDescription());
		sb.append(", descPosition=");
		sb.append(getDescPosition());
		sb.append(", imageLink=");
		sb.append(getImageLink());
		sb.append(", createdDate=");
		sb.append(getCreatedDate());
		sb.append(", createdBy=");
		sb.append(getCreatedBy());
		sb.append(", updatedDate=");
		sb.append(getUpdatedDate());
		sb.append(", updatedBy=");
		sb.append(getUpdatedBy());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("com.nyu.model.Slides");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descPosition</column-name><column-value><![CDATA[");
		sb.append(getDescPosition());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>imageLink</column-name><column-value><![CDATA[");
		sb.append(getImageLink());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdDate</column-name><column-value><![CDATA[");
		sb.append(getCreatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createdBy</column-name><column-value><![CDATA[");
		sb.append(getCreatedBy());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedDate</column-name><column-value><![CDATA[");
		sb.append(getUpdatedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>updatedBy</column-name><column-value><![CDATA[");
		sb.append(getUpdatedBy());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = Slides.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] { Slides.class };
	private long _id;
	private long _originalId;
	private boolean _setOriginalId;
	private String _description;
	private String _descPosition;
	private String _imageLink;
	private Date _createdDate;
	private long _createdBy;
	private Date _updatedDate;
	private long _updatedBy;
	private long _columnBitmask;
	private Slides _escapedModel;
}