package com.nyu.util;

import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PropsUtil;
import com.liferay.util.portlet.PortletProps;

public interface Constant {
	
	public static String SITE_NAME = PortletProps.get("site.name");								//String NY_YOU = "NY-YOU";
	
	
	public static int LESSON_THUMBNAIL_IMAGE_WIDTH = 330;
	
	public static int LESSON_THUMBNAIL_IMAGE_HEIGHT = 173;
	
	public static int PLAYLIST_THUMBNAIL_IMAGE_WIDTH = 330;
	
	public static int PLAYLIST_THUMBNAIL_IMAGE_HEIGHT = 173;
	
	public static int MAX_USER_IMG_FILE_WIDTH_SIZE = 400;
	
	public static int MAX_USER_IMG_FILE_HEIGTH_SIZE = 300;
	
	public static int SlIDE_IMAGE_WIDTH = 570;

	public static int SLIDE_IMAGE_HEIGHT = 230;
	
	public static int MAX_SLIDE_IMAGE_WIDTH = 770;
	
	public static int MAX_SLIDE_IMAGE_HEIGHT = 430;
	
	public static String REQUEST_LESSON_STATUS_OPEN = PortletProps.get("nyu.portlet.request.lesson.status.open");									//"Open";
	public static String REQUEST_LESSON_STATUS_IN_PROGRESS = PortletProps.get("request.lesson.status.in.progress");									//"In Progress";
	public static String REQUEST_LESSON_STATUS_COMPLETE = PortletProps.get("request.lesson.status.complete"); 										//"Complete";
	public static String REQUEST_LESSON_STATUS_ONHOLD = PortletProps.get("request.lesson.status.onhold");											//"On hold";
	public static String REQUEST_LESSON_STATUS_CANCELLED = PortletProps.get("request.lesson.status.cancelled");										//"Cancelled";
	public static int BEST_LESSON_VIEW_COUNT = Integer.parseInt(PortletProps.get("best.lesson.view.count"));										//100;
	public static int BEST_LESSON_APPRECIATE_COUNT = Integer.parseInt(PortletProps.get("best.lesson.appreciate.count"));							//50;
	
	public static String YOUTUBE_URL = PortletProps.get("youtube.url"); 																			//"//www.youtube.com/embed/";
	
	public static String LIFERAY_VENDOR_LESSON_STATUS_DRAFT="draft";
	public static String LIFERAY_VENDOR_LESSON_STATUS_PUBLISH="published";
	public static String LIFERAY_VENDOR_LESSON_PRIVACY_PUBLIC="public";
	public static String LIFERAY_VENDOR_LESSON_PRIVACY_PRIVATE="private";
	public static String LIFERAY_VENDOR_LESSON_PRIVACY_USER="user";
	public static String LIFERAY_VENDOR_LESSON_PRIVACY_VENDOR="NYOU";
	public static String LIFERAY_VENDOR_LESSON_PRIVACY_GROUP="group";
	
	public static String LESSON_ACCESS_VIEWONLY="viewOnly";
	public static String LESSON_ACCESS_CAN_EDIT="canEdit";
	public static String LESSON_ACCESS_NO_ACCESS="noAccess";
	
	public static String LESSON_MEMBER_STATUS_ACCEPTED="accepted";
	public static String LESSON_MEMBER_STATUS_DECLINED="declined";
	public static String LESSON_MEMBER_STATUS_REMOVED="removed";
	public static String LESSON_MEMBER_STATUS_PENDING="pending";
	String LESSON_PERFORM_CLEAN_UP_DELETE_COMMENT = "deleteComment";
	
	public static String KEYWORD_STATUS_ACCEPTED="accepted";
	public static String KEYWORD_STATUS_DECLINED="declined";
	public static String KEYWORD_STATUS_REQUEST="requested";
	
	public static String KEYWORD_MARK_AS_READ="read";
	public static String KEYWORD_MARK_AS_UNREAD="unread";
	
	public static String LESSON_PERMISSION_VIEW_ONLY="view";
	public static String LESSON_PERMISSION_VIEW_REUSE="view_reuse";
	public static String LESSON_PERMISSION_VIEW_REUSE_ATTRIBUTION="view_reuse_attribution";
	
	public static String INAPPROPRIATE="Inappropriate";
	public static String MARKEDAS_RELEASE="release";
	public static String MARKEDAS_QUARANTINE="quarantine";
	public static String LESSON_DELETED_BY_USER = "deletedByUser";
	public static String LESSON_FROM_DELETED_GROUP = "lessonFromDeletedGroup";
	
	public static String ANONYMOUS_NAME = "Anonymous User";
	public static String ANONYMOUS_PIC = "/image/user_male_portrait?img_id=0";
	
	public static String TRANSCRIBE_SPHINX="Sphinx";
	public static String TRANSCRIBE_AUTOMATED="Automated";
	public static String TRANSCRIBE_MANUAL="Manual";
	public static String TRANSCRIBE_NONE="None";
	
	public static String PORTAL_ADMIN_ROLE="nyu-admin";
	
	public static String MYSTUFF_MYFOLLOWERS="myfollowersUrl"; 
	public static String MYSTUFF_MYFOLLOWINGS="myFollowingUrl"; 
	
	public static String PUBLISH_WITH_GROUPPROFILE="publishWithGroupProfile";
	public static String PUBLISH_WITH_USERPROFILE="publishWithUserProfile";
	
	public static String DEFAULT_SEC_TITLE="Enter section title";
	
	public static String PAGE_MY_SUTFF = PortletProps.get("nyu.portlet.page.name.mystuff");								//"/my-stuff";
	public static String PAGE_LESSON_BROWSE = PortletProps.get("nyu.portlet.page.name.page.lesson.browse");				//"/browse";
	public static String PAGE_GROUP = PortletProps.get("nyu.portlet.page.name.page.group");								//"/groups";
	public static String PAGE_REQUEST_LESSON = PortletProps.get("nyu.portlet.page.name.page.request.lesson");			//"/requests";
	public static String PAGE_CONTRIBUTOR = PortletProps.get("nyu.portlet.page.name.page.contributor");					//"/contributor";
	public static String PAGE_HOME = PortletProps.get("nyu.portlet.page.name.page.home");								//"/home";
	public static String PAGE_CREATE_LESSON = PortletProps.get("nyu.portlet.page.name.page.create.lesson");				//"/create-lesson";
	public static String PAGE_CONFIGURATION = PortletProps.get("nyu.portlet.page.name.page.configuration");				//"/configuration";
	public static String PAGE_TRENDING = PortletProps.get("nyu.portlet.page.name.page.trending");						//"/trending";
	
	
	public static String PORTLET_MY_SUTFF = "myStuff_WAR_nyyouportlet";
	public static String PORTLET_LESSON = "lessons_WAR_nyyouportlet";
	public static String PORTLET_GROUP = "group_WAR_nyyouportlet";
	public static String PORTLET_USERGROUP = "userGroup_WAR_nyyouportlet";
	public static String PORTLET_REQUEST_LESSON = "requestlesson_WAR_nyyouportlet";
	public static String PORTLET_CONTRIBUTOR = "contributor_WAR_nyyouportlet";
	public static String PORTLET_CREATE_LESSON = "nyulessons_WAR_nyyouportlet";
	public static String PORTLET_ADMIN = "admin_WAR_nyyouportlet";
	public static String PORTLET_VIEW_LESSON = "viewlesson_WAR_nyyouportlet";
	public static String PORTLET_TRENDING = "trending_WAR_nyyouportlet";
	
	
	
	
	public static String POPULAR="Popular";
	public static String LATEST="Latest";
	public static String ANSWERED="Answered";
	public static String OPEN="Open";
	
	public static String REQUEST_COLLOBORATION="req_Collaborator";
	public static String REQUEST_INFORMATION="req_Information";
	public static String REQUEST_LESSON="req_Lesson";
	public static String REQUEST_OPINION="req_Opinion";
	
	public static String SURVEYMONKEY_URLPATTERN = PortletProps.get("survey.monkey.url.pattern");									//"https://www.surveymonkey.com";
	public static String QUALTRICS_URLPATTERN =	PortletProps.get("qualtrics.url.pattern");											//"https://nyu.qualtrics.com/SE/?SID=";
	public static String QUALTRICS_URL = PortletProps.get("qualtrics.url"); 														//"https://nyu.qualtrics.com";
	
	String VENDOR_COMP_PLACEHOLDER_GROUP_IMAGE = PortletProps.get("ny.you.placeholder.group.image");
	
	//added by asif 11/09/2015
	
	String COMMON_THEME_IMAGE_PATH = "/ny-you-theme/images/";	
	String VENDOR_NAME = "commons"; 
	
	public static String CURRENT_OWNER = PropsUtil.get("current.portal.owner");
	public static String CURRENT_BRAND_NAME = PropsUtil.get("current.brand.name.to.display");
	
	public static String LESSON_CARD_PLACEHOLDER = "lesson_placeholder.png";
	public static String GROUP_CARD_PLACEHOLDER = "group_placeholder.png";
	public static String CONTENT_PREVIEW_PLACEHOLDER = "content_preview.jpg";
	
		//getting value from portal.properties that this portlet is for which company.
	String HEADER_CONFIGURATION_JSP = "/WEB-INF/jsp/header/configuration.jsp";
	String LESSONS_USER_STATS_JSP = "/WEB-INF/jsp/lessons/userStats.jsp";
	String LESSONS_AUTHOR_LESSON_JSP = "/WEB-INF/jsp/lessons/authorLesson.jsp";
	String LESSONS_INCLUDE_RESULTS_JSP = "/WEB-INF/jsp/lessons/includeResults.jsp";
	String MYSTUFF_MY_FOLLOWER_JSP = "/WEB-INF/jsp/mystuff/myFollower.jsp";
	String MYSTUFF_MY_POINTS_JSP = "/WEB-INF/jsp/mystuff/myPoints.jsp";
	String MYSTUFF_CATEGORY_TAGS_LESSONS_JSP = "/WEB-INF/jsp/mystuff/categoryTagsLessons.jsp";
	String MYSTUFF_MY_BADGES_JSP = "/WEB-INF/jsp/mystuff/myBadges.jsp";
	String MYSTUFF_MY_FOLLOWING_JSP = "/WEB-INF/jsp/mystuff/myFollowing.jsp";
	
	
	String VIEWLESSON_VIEWLESSON = "viewLesson";
	String USER_PROFILE_VIEW_JSP = "view";
	String USER_PROFILE_USER_PROFILE_PIC_JSP = "user_profile_pic";
	String USER_PROFILE_FILE_UPLOAD = "fileUpload";
	
	//Expando fields 
	String EXPANDO_FIELD_ANONYMOUS_USER = "anonymous-user";
	String EXPANDO_FIELD_AUTHOR_INFO = "author-info";
	String EXPANDO_FIELD_VENDOR_ALUMNI = "nyu-alumni";
	String EXPANDO_FIELD_VENDOR_SCHOOL = "nyu-school";
	String EXPANDO_FIELD_YEAR_OF_PASSING = "year-of-passing";
	String EXPANDO_FIELD_SUBSCRIBE_MAIL_DIGEST = "subscribe-email-digest";
	String EXPANDO_FIELD_NOTIFY_EMAIL_DIGEST = "nofity-email-digest";
	String EXPANDO_FIELD_CUSTOM_GENDER = "custom-gender";
	String EXPANDO_FIELD_AGREE_DATE = "agree-date";
	String EXPANDO_FIELD_MARITAL_STATUS = "marital-status";
	String EXPANDO_FIELD_RACE = "race";
	String EXPANDO_FIELD_ANNUAL_INCOME = "annual-household-income-range";
	String EXPANDO_FIELD_HEALTH_INSURANCE = "have-health-insurance?";
	String EXPANDO_FIELD_HIGHEST_EDUCATION = "highest-level-of-education-completed";
	String EXPANDO_FIELD_ZIPCODE = "zipcode";

	String GROUP_ABOUT = "groupAbout";
	String PRIMARY_KEY_GROUP_ID = "primaryKey.groupId";
	String TAG_ADD_LESSONS = "tagAddLessons";
	String TAG_HEADER_CLASS_MESSAGE_HEADING = "<h4 class='message-heading'> ";
	String ACCEPT_TO_GROUP_JOIN = "AcceptToGroupjoin";
	String DECLINE_TO_GROUP_JOIN = "DeclineToGroupjoin";
	String CATEGORY_ADD_LESSONS = "categoryAddLessons";
	String USER_GROUP_GROUPS_JSP = "groups";
	String USER_GROUP_GROUP_THUMBNAIL_JSP = "groupThumbnail";
	String USER_GROUP_GROUP_ANNOUNCEMENT_FORM_JSP = "groupAnnoumcementForm";
	String USER_GROUP_GROUP_DETAIL_JSP = "groupDetail";
	String USER_GROUP_CREATE_GROUP__JSP = "createGroup";
	String USER_GROUP_EDIT_GROUP_JSP = "editGroup";
	String USER_GROUP_ADD_LESSON_TO_GROUP = "addLessonToGroup";
	String USER_GROUP_UPDATE_GROUP_VAR = "Update Group";
	String USER_GROUP_GROUPS_VAR = "Groups";
	String USER_GROUP_CREATE_GROUP_VAR = "Create Group";
	String USER_GROUP_DELETE_GROUP_VAR = "Delete Group";
	String USER_GROUP_UPLOAD_TIMES_VAR = "uploadedTime";
	String USER_GROUP_GROUP_DELETED_SUCCESSFULLY = "Group deleted successfully.";
	String USER_GROUP_REQUEST_DECLINED_TO_JOIN_GROUP = "content/templates/"+CURRENT_OWNER+"/requestDeclinedToJoinGroup.vm";		
	String DECLINE_INVITATION_TO_LESSON_VM = "content/templates/"+CURRENT_OWNER+"/declineInvitationToLesson.vm";				
	String INVITE_USER_TO_LESSON_VM = "content/templates/"+CURRENT_OWNER+"/inviteUserToLesson.vm";								
	String QURANTINE_LESSON_VM = "content/templates/"+CURRENT_OWNER+"/qurantineLesson.vm";										
	String RELEASE_LESSON_VM = "content/templates/"+CURRENT_OWNER+"/releaseLesson.vm";											
	String LESSON_MADE_AS_INAPPROPRIATE_VM = "content/templates/"+CURRENT_OWNER+"/lessonMadeAs Inappropriate.vm";				
	String USER_GROUP_REQUEST_TO_JOIN_GROUP = "content/templates/"+CURRENT_OWNER+"/requestToJoinGroup.vm";						
	String USER_GROUP_REQUEST_TO_ACCEPRTED_TO_JOIN_GROUP = "content/templates/"+CURRENT_OWNER+"/requestAcceptedToJoinGroup.vm";		
	String USER_GROUP_GROUP_RESULTS_JSP = "/WEB-INF/jsp/userGroup/groupResults.jsp";
	String USER_GROUP_DISCUSSION_RESULTS_JSP = "/WEB-INF/jsp/userGroup/discussionResults.jsp";
	String USER_GROUP_INVITE_USER_TO_GROUP = "content/templates/whitelabel/inviteUserToGroup.vm";					
	String USER_GROUP_ACCEPT_INVITATION_TO_GROUP = "content/templates/"+CURRENT_OWNER+"/acceptInvitationToGroup.vm";
	String USER_GROUP_DECLINE_INVITATION_TO_GROUP = "content/templates/"+CURRENT_OWNER+"/declineInvitationToGroup.vm";
	String CONTENT_TEMPLATES_EMAIL_DIGEST_TO_USER_VM = "content/templates/"+CURRENT_OWNER+"/emailDigestToUser.vm";			
	String TRENDING_ANONYMOUS_USER = "ANONYMOUS USER";
	String TRENDING_JSP = "trending";
	String TRENDING_DATA_FILE_ONE_JSON = "data/data-file-1.json";
	String TRENDING_REG_EX = "[^a-zA-Z0-9_-]";
	
	//SOCIAL_ACTIVITIES 
	String SOCIAL_ACTIVITIES_PROFILE_PATH = "/profile";
	
	String REQUEST_LESSON_VIEW_JSP = "view";
	String REQUEST_LESSON_CREATE_REQUEST_JSP = "createRequest";
	String REQUEST_LESSON_SUBJECT_JSP = "subject";
	String REQUEST_LESSON_REQUEST_FOR_INFO = "request-for-info";
	String REQUEST_LESSON_REQ_COLLABORATION = "req_Collaboration";
	String REQUEST_LESSON_CLASS_NAME = "RequestLesson";
	String AUDIT_REPORT_EVENT_TYPE_CREATE = "Create Request";
	String AUDIT_REPORT_EVENT_TYPE_DELETE = "Delete Request";
	String AUDIT_REPORT_EVENT_TYPE_VIEW = "View Request";
	String REQUEST_LESSON_MY_LESSON_JSP = "myLessons";
	String REQUEST_LESSON_MY_FAVOURITE_LESSONS_JSP = "myFavouriteLessons";
	String REQUEST_LESSON_EMAIL_JSP = "email";
	String REQUEST_LESSON_DOCUMENTS = "documents";
	
	String COMMON_STRING_CONSTANT_ALL_REQUEST_JSON = "allRequestJson";
	String COMMON_STRING_CONSTANT_MY_REQUEST = "myRequest";
	String COMMON_STRING_CONSTANT_SUBJECT_JSON = "subjectJson";
	String COMMON_STRING_CONSTANT_REQUEST_LESSON_ID = "requestLessonId";
	String COMMON_STRING_CONSTANT_REQUEST_ID = "requestId";
	String COMMON_STRING_CONSTANT_REQUEST_LESSON_JSON = "requestLessonJson";
	String COMMON_STRING_CONSTANT_ANSWER_JSON = "answerJson";
	String COMMON_STRING_CONSTANT_COMMENTS_JSON = "commentsJson";
	String COMMON_STRING_CONSTANT_ANSWER_COMMENTS_JSON = "answerCommentsJson";
	String COMMON_STRING_CONSTANT_LESSONS = "lessons";
	String COMMON_STRING_CONSTANT_ANSWER = "answer";
	String COMMON_STRING_CONSTANT_ANSWER_TYPE = "answerType";
	String COMMON_STRING_CONSTANT_MY_LESSON_IDS = "myLessonIds";
	String COMMON_STRING_CONSTANT_MY_FAV_LESSON_IDS = "myFavLessonIds";
	String COMMON_STRING_CONSTANT_BODY = "body";
	String COMMON_STRING_CONSTANT_ANSWER_ID = "answerId";
	String COMMON_STRING_CONSTANT_COLLABORATION_ID = "collaborationId";
	String COMMON_STRING_CONSTANT_SURVEY_URL = "surveyUrl";
	String COMMON_STRING_CONSTANT_GROUPS = "groups";
	String COMMON_STRING_CONSTANT_CLASS_NAME_ID = "classNameId";
	String COMMON_STRING_CONSTANT_CLASS_PK = "classPK";
	String COMMON_STRING_CONSTANT_CREATE_DATE = "createDate";
	String COMMON_STRING_CONSTANT_COMMENT_ID = "commentId";
	String COMMON_STRING_CONSTANT_COLLABORATION_LESSON_JSON = "colloborateLessonJson";
	String COMMON_STRING_CONSTANT_OPINION_SURVEY = "opinionSurvey";
	String COMMON_STRING_CONSTANT_OPTION_NAME = "optionName";
	String COMMON_STRING_CONSTANT_PERCENTAGE = "percentage";
	String COMMON_STRING_CONSTANT_PARTICIPATION_SIZE = "participationSize";
	String COMMON_STRING_CONSTANT_ALL_LESSONS = "allLessons";
	String COMMON_STRING_CONSTANT_NAME = "name";
	String COMMON_STRING_CONSTANT_OPINION_SURVEY_LINK = "opnionSurveyLink";
	String COMMON_STRING_CONSTANT_SEND_TO = "sendTo";
	String COMMON_STRING_CONSTANT_CREATED_BY = "createdBy";
	String COMMON_STRING_CONSTANT_USER_GROUPS = "usergroups";
	String COMMON_STRING_CONSTANT_REQUEST_TYPE = "requestType";
	String COMMON_STRING_CONSTANT_USER_NAME = "userName";
	String COMMON_STRING_CONSTANT_USER_ID = "userId";
	String COMMON_STRING_CONSTANT_APPRECIATED_COUNT = "appreciatedCount";
	String COMMON_STRING_CONSTANT_CHECKED = "checked";
	String COMMON_STRING_CONSTANT_HAS_APPRECIATED = "hasAppreciated";
	String COMMON_STRING_CONSTANT_DESCRIPTION = "description";
	String COMMON_STRING_CONSTANT_DOCUMENT_PATH = "documentPath";
	String COMMON_STRING_CONSTANT_OPINION_SURVEY_LINK_II = "opinionSurveyLink";
	String COMMON_STRING_CONSTANT_SURVEY_RESULT_LINK = "surveyResultLink";
	String COMMON_STRING_CONSTANT_CATEGORIES = "categories";
	String COMMON_STRING_CONSTANT_LESSON_AUTHOR_ID = "lessonAuthorId";
	String COMMON_STRING_CONSTANT_LESSON_AUTHOR = "lessonAuthor";
	String COMMON_STRING_CONSTANT_LESSON_DESCRIPTION = "lessonDescription";
	String COMMON_STRING_CONSTANT_THUMBNAIL_PATH = "thumbnailPath";
	String COMMON_STRING_CONSTANT_LESSON_NAME = "lessonName";
	String COMMON_STRING_CONSTANT_LESSON_ID = "lessonId";
	String COMMON_STRING_CONSTANT_GET_ANSWER_JSON = "getAnswerJson";
	String COMMON_STRING_CONSTANT_GET_OPINION_SURVEY = "getOpinionSurvey";
	String COMMON_STRING_CONSTANT_TAGS = "tags";
	String COMMON_STRING_CONSTANT_CATEGORY_ID = "categoryId";
	String COMMON_STRING_CONSTANT_CREATE_DATE_II = "crateDate";
	char CHAR_COMMA = ',';
	char CHAR_SPACE =' ';
	String COMMON_STRING_CONSTANT_ANSWER_COUNT = "answerCount";
	String COMMON_STRING_CONSTANT_IS_CHECKED = "isChecked";
	String COMMON_STRING_CONSTANT_COLLOBORATION_ID = "colloborationId";
	String COMMON_STRING_CONSTANT_ANSWER_COMMENT_ID = "answerCommentId";
	String COMMON_STRING_CONSTANT_REQUEST_COMMENT_ID = "requestCommentId";
	String COMMON_STRING_CONSTANT_USER_GROUP_ID = "userGroupId";
	String COMMON_STRING_CONSTANT_GROUP_ID = "groupId";
	String COMMON_STRING_CONSTANT_CREATED_DATE = "createdDate";
	String COMMON_STRING_CONSTANT_TAG_ID = "tagId";
	String COMMON_STRING_CONSTANT_ANSWERED_BY = "answeredBy";
	String COMMON_STRING_CONSTANT_ANSWERED_REQUEST_ID = "answerRequestId";
	String COMMON_STRING_CONSTANT_EMAIL_REQ_LESSON_ID = "emailReqLessonId";
	String COMMON_STRING_CONSTANT_TO_ADDRESS = "toAddress";
	String COMMON_STRING_CONSTANT_MESSAGE = "message";
	String QUOTE_DOT = "\". ";
	String COMMON_STRING_CONSTANT_DURATION = "duration";
	String COMMON_STRING_CONSTANT_LESSON_STATUS = "lessonStatus";
	String COMMON_STRING_CONSTANT_EMAIL_ADDRESS = "emailAddress";
	String COMMON_STRING_CONSTANT_URL = "url";
	String COMMON_STRING_CONSTANT_DOUBLE_NEW_LINE = "\n\n";
	String COMMON_STRING_CONSTANT_ICON_GLOBE = "icon-globe";
	String COMMON_STRING_CONSTANT_ICON_USER = "icon-user";
	String VENDOR_COMP_IMAGE_PLACEHOLDER_PNG = PortletProps.get("ny.you.image.placeholder");
	String IMAGE_LAYOUT_SET_LOGO_IMG_ID = PortletProps.get("image.layout.set.logo.img.id");
	String VENDOR_FROM_ADDRESS_MAIL = PortletProps.get("nyu.you.from.address.mail");
	String PORTLET_PROP_REQUEST_COURSE_ID_PREP = PortletProps.get("request.course.id.prep");
	String PORTLET_PROP_RESOURCE_SPACE_PREVIEW_GENERATE_URL = PortletProps.get("resource.space.preview.generate.url");
	String PORTLET_PROP_RESOURCE_SPACE_PREVIEW_KEY = PortletProps.get("resource.space.preview.key");
	String PORTLET_PROP_ENGAGE_LAUNCH_URL = PortletProps.get("engage.launch.url");
	String PORTLET_PROP_LAUNCHER_KEY = PortletProps.get("launcher.key");
	String PORTLET_PROP_SITE_MESSAGE_REPORT = PortletProps.get("site.message.report");
	String COMMON_VENDOR_ENGAGE_SUPPORTED_TYPES = PortletProps.get("nyu.engage.supported.types");
	String PORTLET_PROP_ADMIN_CONTACTUS_TO_ADDRESS = PortletProps.get("admin.contactus.to.address");
	String PORTLET_PROP_ADMIN_CONTACTUS_TYPE = PortletProps.get("admin.contactus.type");
	String PORTLET_PROP_DAM_SECRET_KEY = PortletProps.get("dam.secret.key");
	String PORTLET_PROP_SHOW_LESSONS_COUNT_VALUE = PortletProps.get("show.lessons.count.value");
	String PORTLET_PROP_RESOURCE_SPACE_PREVIEW_URL = PortletProps.get("resource.space.preview.url");
	String PORTLET_PROP_CONTEXT_NAME = PortletProps.get("ny.you.portlet");
	String PORTLET_PROP_SITE_NAME_PORTLET_IMAGE_TEMP = PortletProps.get("site.name.portlet.images.temp");
	String PORTLET_PROP_SHOW_MORE_LESSONS_COUNT = PortletProps.get("show.more.lessons.count");
	String PORTLET_PROP_LIFERAY_SITE_BASNO_APP_SECRET_KEY = PortletProps.get("liferay.nyu.basno.app.secret.key");
	String PORTLET_PROP_LIFERAY_SITE_BASNO_APP_SECRET_KEY_VALUE = PortletProps.get("liferay.nyu.basno.app.secret.key.value");
	String PORTLET_PROP_LIFERAY_SITE_BASNO_APP_ID = PortletProps.get("liferay.nyu.basno.app.id");
	String PORTLET_PROP_LIFERAY_SITE_BASNO_APP_URL = PortletProps.get("liferay.nyu.basno.app.url");
	String PORTLET_PROP_ENGAGE_REMOVE_MEDIA_URL = PortletProps.get("ENGAGE_REMOVE_MEDIA_URL");
	String PORTLET_PROP_ENGAGE_RECORDER_URL = PortletProps.get("ENGAGE_RECORDER_URL");
	String PORTLET_PROP_CURRENT_SERVER_HOST = PortletProps.get("current.server.host");
	String PORTLET_PROP_EMAIL_DIGEST_NUMBER_OF_DAYS_NOT_LOGIN = PortletProps.get("email.digest.number.of.days.not.login");
	String PORTLET_PROP_SITE_THEME_IMAGES = PortletProps.get("site.theme.images");
	String PORTLET_PROP_SITE_NAME_SMALL = PortletProps.get("site.name.small");
	String PORTLET_PROP_SITE_NAME_CAPITAL = PortletProps.get("site.name.capital");
	String PORTLET_PROP_LIFERAY_SITE_EXISTING_REQUEST_SEARCH_WORD = PortletProps.get("liferay.nyu.existingRequest.searchWord");
	//CHECK
	String PORTLET_PROP_VENDOR_BASNO_APP_BADGE_ID = PortletProps.get("liferay.nyu.basno.app.badge.id.9242");
	String PORTLET_PROP_VENDOR_BASNO_APP_BADGE_TARGET = PortletProps.get("liferay.nyu.basno.app.badge.target");
	String PORTLET_PROP_VENDOR_BASNO_APP_BADGE_ID_FOUR_FOUR = PortletProps.get("liferay.nyu.basno.app.badge.id.9244");
	String PORTLET_PROP_VENDOR_BASNO_APP_BADGE_YEAR_TARGET = PortletProps.get("liferay.nyu.basno.app.badge.year.target");
	String PORTLET_PROP_VENDOR_RESOURCESPACE_URL = PortletProps.get("liferay.nyu.resourcespace.url");
	String PORTLET_PROP_PATH_VENDOR = "/commons/";
	String PORTLET_PROP_VENDOR_PORTLET_IMAGES = PortletProps.get("vendor.portlet.images");
	String PORTLET_PROP_GROUP_SLASH_VENDOR = PortletProps.get("group.slash.vendor");
	String PORTLET_PROP_PORTLET_THEME = PortletProps.get("portlet.theme");
	String PORTLET_PROP_NAME_OF_PORTLET = PortletProps.get("name.of.portlet");
	String PORTLET_PROP_VENDOR_VENDOR_GTS_COM = PortletProps.get("vendor.vendorgts.com");
	String PORTLET_PROP_ONLY_VENDOR_NAME = PortletProps.get("only.vendor.name");
	String PORTLET_PROP_CAPITAL_ONLY_VENDOR_NAME = PortletProps.get("capital.only.vendor.name");
	
	String COMMON_STRING_CONSTANT_ICON_GROUP = "icon-group";
	String COMMON_STRING_CONSTANT_THREE_DOTS = "...";
	String COMMON_STRING_CONSTANT_ACTION = "action";
	String GOROUP_PRIVACY = "group-privacy";
	String APPRECIATE = "appreciate"; 
	String USER_PERMISSION_TO_ACCESS = "userPermissionToAccess";	
	String COMMON_STRING_CONSTANT_PRIVACY = "privacy";
	String COMMON_STRING_CONSTANT_PERMISSION = "permission";
	String COMMON_STRING_CONSTANT_LESSON_PRIVACY = "lessonPrivacy";
	String COMMON_STRING_CONSTANT_PERMISSION_ICON = "permissionIcon";
	
	String COMMON_STRING_CONSTANT_PERMISSION_TOOL_TIP = "permissionTooltip";
	String COMMON_STRING_CONSTANT_GROUP_PATH_DOCUMENT_PATH = "groupPathDocumentPath";
	String COMMON_STRING_CONSTANT_USER_GROUP_NAME = "userGroupName";
	String COMMON_STRING_CONSTANT_USER_IMAGE = "userImage";
	String COMMON_STRING_CONSTANT_CONTENT = "content";
	String COMMON_STRING_CONSTANT_ENTRY_ID = "entryId";
	String COMMON_STRING_CONSTANT_TITLE = "title";
	String COMMON_STRING_CONSTANT_EXPIRATION_DATE = "expirationDate";
	String COMMON_STRING_CONSTANT_VIOLATING_SECTION = "voilatingSection";
	String COMMON_STRING_CONSTANT_EXTENSION = "extension";
	String COMMON_STRING_CONSTANT_DOCUMENT_NAME = "documentName";
	String COMMON_STRING_CONSTANT_RESOURCE_DATA = "resourceData";
	String COMMON_STRING_CONSTANT_PRIVACY_CHECK_MESSAGE = "privacyCheckMessage";
	String COMMON_STRING_CONSTANT_REF_ID = "refId";
	String COMMON_STRING_CONSTANT_RESOURCE_SPACE = "resourceSpace";
	String COMMON_STRING_CONSTANT_TAGS_SELECTED_NAMES = "tagsSelectedNames";
	String COMMON_STRING_CONSTANT_LAST_VIEW_DATE = "lastViewDate";
	String COMMON_STRING_CONSTANT_CLASS_NAME = "className";
	String COMMON_STRING_CONSTANT_EVENT_TYPE = "eventType";
	String CLASSPATH_RESOURCE_LOADER_CLASS = "classpath.resource.loader.class";
	String COMMON_STRING_CONSTANT_CLASS_PATH = "classpath";
	
	String COMMON_STRING_CONSTANT_CATEGORIES_SELECTED_IDS = "categoriesSelectedIds";
	String COMMON_STRING_CONSTANT_RESOURCE_SPACE_STRING = "resource space";
	String COMMON_STRING_CONSTANT_RESOURCE_ID = "resourceId";
	String COMMON_STRING_CONSTANT_FORWARD_SLASH_LESSON_ID = "/lessonId/";
	String COMMON_STRING_CONSTANT_PUBLISHED_PROFILE = "publishedProfile";
	String COMMON_STRING_CONSTANT_ENGAGE_SLASH_LAUNCHER = "/engage/launcher";
	String COMMON_STRING_CONSTANT_EDIT_LESSON = "editLesson";
	String COMMON_STRING_CONSTANT_ICON_SHARE_ALT = "icon-share-alt";
	String COMMON_STRING_CONSTANT_ICON_LOCK = "icon-lock";
	String COMMON_STRING_CONSTANT_ICON_UNLOCK = "icon-unlock";
	String COMMON_STRING_CONSTANT_TRUE = "true";
	String COMMON_STRING_CONSTANT_FALSE = "false";
	String COMMON_STRING_CONSTANT_IS_CHECKED_LOWER = "ischecked";	
	String COMMON_LESSON_THUMBNAIL = "lessonThumbnail";
	String COMMON_AUTHOR_NAME = "authorName";
	String COMMON_CITATION_LESSON_NAME = "citationLessonName";
	String COMMON_ABOUT_AUTHOR = "aboutAuthor";
	String COMMON_AUTHOR_IMG = "authorImg";
	String COMMON_DOCUMENT_SECTION = "documentSection";
	String COMMON_VIEW_COUNT = "viewCount";
	String COMMON_HAS_APPRECIATED = "hasappreciated";
	String COMMON_HAS_ADMIN_RIGHTS = "hasAdminRights";
	String COMMON_IS_LESSON_OWNER = "isLessonOwner";
	String COMMON_IS_CO_AUTHOR = "isCoAuthor";
	String COMMON_EDIT_URL = "editUrl";
	String COMMON_CONTRIBUTOR_URL = "contributorUrl";
	String COMMON_SHOW_SCRIPT_VALUES = "showScriptValues";
	String COMMON_NO = "no";
	String COMMON_SHOW_DOCUMENT = "showDocument";
	String COMMON_DONT_HAVE_PERMISSION = "dontHavePermission";
	String COMMON_LESSON_DURATION = "lessonDuration";
	String COMMON_CITATION_DATE = "citationDate";
	String COMMON_HIDDEN_USER_GROUP_IDS = "hiddenUserGroupIds";
	String COMMON_USER_GROUP_ARRAY = "userGroupArray";
	String COMMON_HIDDEN_USER_IDS = "hiddenUserIds";
	String COMMON_USER_ARRAY = "userArray";
	String COMMON_ORDER = "order";
	
	String COMMON_RESOURCE_ID = "/resourceId/";
	String COMMON_RESOURCE = "resource";
	String COMMON_YOUTUBE = "youtube";
	String COMMON_HTTP_IMG_YOUTUBE_COM_VI = "http://img.youtube.com/vi/";
	String COMMON_ID = "id";
	String COMMON_LOGGED_IN_USER = "loggedInUser";
	String COMMON_EMAIL_DIGEST_STATUS = "emailDigestStatus";
	String COMMON_NOTIFY_EMAIL_DIGEST = "notifyEmaildigest";
	String COMMON_ALUMNI_STATUS = "alumniStatus";
	String COMMON_MALE = "male";
	String COMMON_FEMALE = "female";
	String COMMON_NTD = "ntd";
	String COMMON_USER_PROFILE_JOB_TITLE = "userProfileJobTitle";
	String COMMON_CUSTOM_GENDER = "customGender";
	String COMMON_SUCESS = "sucess";
	String COMMON_CROP_REGION = "cropRegion";
	String HEIGHT = "height";
	String WIDTH = "width";
	String COMMON_X = "x";
	String COMMON_Y = "y";
	String COMMON_PREFIX_LIST = "prefixList";
	String COMMON_SUFFIX_LIST = "suffixList";
	String COMMON_GENDER = "gender";
	String COMMON_GENDER_VALUE = "genderValue";
	String COMMON_CUSTOMISED_GENDER_VALUE = "customisedGenderValue";
	String COMMON_MM_DD_YYYY_DATE_FORMAT = "MM/dd/yyyy";
	String COMMON_BD_DAY = "bdDay";
	String COMMON_BD_MONTH = "bdMonth";
	String COMMON_BD_YEAR = "bdYear";
	String COMMON_STRING_ZERO = "0";
	String COMMON_SCREEN_NAME = "screenName";
	String COMMON_FIRST_NAME = "firstName";
	String COMMON_LAST_NAME = "lastName";
	String COMMON_MIDDLE_NAME = "middleName";
	String COMMON_EXPANDO_ATTRIBUTE_VENDOR_SCHOOL = "ExpandoAttribute--nyu-school--";
	String COMMON_EXPANDO_ATTRIBUTE_ANONUMOUS_USER = "ExpandoAttribute--anonymous-user--";
	String COMMON_EXPANDO_ATTRIBUTE_AUTHOR_INFO = "ExpandoAttribute--author-info--";
	String COMMON_EXPANDO_ATTRIBUTE_YEAR_OF_PASSING = "ExpandoAttribute--year-of-passing--";
	String COMMON_EXPANDO_ATTRIBUTE_MARITAL_STATUS = "ExpandoAttribute--marital-status--";
	String COMMON_EXPANDO_ATTRIBUTE_RACE = "ExpandoAttribute--race--";
	String COMMON_EXPANDO_ATTRIBUTE_ANNUAL_INCOME = "ExpandoAttribute--annual-household-income-range--";
	String COMMON_EXPANDO_ATTRIBUTE_HEATH_INSURANCE = "ExpandoAttribute--have-health-insurance?--";
	String COMMON_EXPANDO_ATTRIBUTE_HIGHEST_EDUCATION = "ExpandoAttribute--highest-level-of-education-completed--";
	String COMMON_EXPANDO_ATTRIBUTE_ZIPCODE = "ExpandoAttribute--zipcode--";
	String COMMON_SUBSCRIBE_EMAIL_DIGEST = "subscribeEmailDigest";
	String COMMON_EMAIL_DIGEST_INACTIVE = "emailDigestInactive";
	String COMMON_VENDOR_ALUMNI = "nyuAlumni";
	String COLLABORATION_REQUEST_ID = "collaborationRequestId";
	String BASIC_LESSON = "basicLesson";
	String CHOOSE_LESSON_TYPE = "chooseLessonType";
	String PUBLISH_WITH_PROFILE = "publishWithProfile";
	String LESSON = "lesson";
	String FROM_PREVIEW_EDIT = "fromPreviewEdit";
	String LESSON_OBJECTIVES = "lessonObjectives";
	String CATEGORY_IDS = "categoryIds";
	String TAG_NAMES = "tagNames";
	String JSON_LESSONS = "jsonLessons";
	String USER_GROUP_JSON = "userGroupJson";
	String CREATE_ADVANCE_LESSON = "createAdvanceLesson";
	String NO_BASIC_LESSON = "noBasicLesson";
	String JSON_VENDOR_LESSON_OBJECTIVES = "jsonNyuLessonObjectives";
	String LESSON_MODE = "lessonMode";
	String RESOURCE_ID_ARRAY = "resourceIdArray";
	String COURSE_ID = "courseId";
	String ADVANCE_LESSON_CONTENT = "advanceLessonContent";
	String REQUEST_LESSON_CHECK = "requestLessonCheck";
	String COMMON_REQUEST_LESSON = "requestLesson";
	String CLOSED = "Closed";
	String YES = "yes";
	String EDIT = "edit";
	String LESSON_THUMBNAIL = "LessonThumbnail";
	String IMAGE = "image";
	String JPEG = "jpeg";
	String DETAIL_SAVE_SUCCESS = "detailSaveSuccess";
	String LESSONS_HYPHEN_THUMBNAIL = "Lessons-Thumbnail";
	String OBJECTIVE = "objective";
	String OBJECTIVE_ID = "objectiveId";
	String CLEAR_TEMP_ONLY = "clearTempOnly";
	String SECTION_TITLE = "sectionTitle";
	String EMBED_URL = "embedUrl";
	String RESOURCE_TYPE = "resourceType";
	String UPDATE = "update";
	String ADD = "add";
	String EXISTING_IDS = "existingIds";
	String CURRENT_SEC_IDS = "currentSecIds";
	String SECTION_ID = "sectionId";
	String DOCUMENT_ID = "documentId";
	String SECTION_LENGTH = "sectionLength";
	String SECTION_INDEX = "sectionIndex";
	String LEARNING_OBJ_IDS = "learningObjIds";
	String AUTO_SAVE = "autoSave";
	String EMBED = "embed";
	String NARRATIVE = "narrative";
	String SECTION_ORDER = "sectionOrder";
	String YOUTU_BE = "youtu.be";
	String RESOURCE_REPLACED = "resourceReplaced";
	String DOC_UPLOAD_TYPE = "docUploadType";
	String EXISTING = "existing";
	String DOC_TITLE = "docTitle";
	String IMAGE_URL = "imageUrl";
	String DOC_UUID = "docUuid";
	String DOC_AUTO_TRANSCRIPT = "docAutoTranscript";
	String DOC_DESCRIPTION = "docDescription";
	String STRING_SERVICE_CONTEXT = "serviceContext";
	String SHARE = "share";
	String PRIVATE_TYPE = "privateType";
	String PRIVATE_VALUE = "privateValue";
	String LESSON_URL = "lessonUrl";
	String IS_CREATE_LESSON = "isCreateLesson";
	String PUBLISH_LISTENER_DESTINATION = "publish-listener-destination";
	String EDIT_LESSON_SAVED = "editLessonSaved";
	String YOUTUBE_COM = "youtube.com";
	String DOCUMENT_SECTION_LIST = "documentSectionList";
	String SECTION_AND_DOC_ID_ARRAY = "sectionAndDocIdArray";
	String LESSON_IMG = "lessonImg";
	String IS_EDIT_MODE = "isEditMode";
	String OPEN_CONTENT_IN_EDIT = "openContentInEdit";
	String CONTENT_SAVED_SUCCESS = "contentSavedSuccess";
	String REQUEST_LESSONS = "requestedLessons";
	String DETAIL_SAVED_SUCCESS = "detailsSavedSuccess";
	String EDIT_ADVANCE_LESSON = "editAdvanceLesson";
	String PREVIEW_EDIT = "previewEdit";
	String DROP_DOWN_ID = "dropDownId";
	String DD_HYPHEN = "dd-";
	String DROP_DOWN_VALUE = "dropDownValue";
	String USER_IMG = "userImg";
	String COMMENT = "comment";
	String LESSON_ADMIN = "lessonAdmin";
	String LESSON_ADMIN_NAME = "lessonAdminName";
	String LESSON_ADMIN_EMAIL = "lessonAdminEmail";
	String MEMBER = "members";
	String USER_LIST_JSON = "userListJson";
	String USER_DROP_DOWN_ARRAY = "userDropDownArray";
	String USER_COMMENTS_ARRAY = "userCommentsArray";
	String TYPE = "type";
	String ADDITIONAL_DATA = "additionalData";
	String DECLINE_TO_MANAGE_LESSON = "DeclineToManageLesson";
	String COMMON_DATE = "date";
	String FROM = "from";
	String TO = "to";
	String LESSON_HYPER_LINK = "lessonHyperLink";
	String CONTENT_TEMPLATES_ACCEPT_INVITATION_TO_LESSON = "content/templates/"+CURRENT_OWNER+"/acceptInvitationToLesson.vm";			
	String USER_NOTIFICATION_EVENT_ID = "userNotificationEventId";
	String ACCEPT_TO_MANAGE_LESSON = "AcceptToManageLesson";
	String DOT_MP4 = ".mp4";
	String DOT_SCORM = ".scorm";
	String DOT_ZIP = ".zip";
	String SCORM = "scorm";
	String HTTPS_DOUBLE_SLASH = "https://";
	String HTTPS_COLON = "https:";
	String MP_FOUR = "mp4";
	String AUTHOR_ID = "authorId";
	String CHAPTER_ID = "chapterId";
	String LESSON_IDS = "lessonIds";
	String COMMON_KEY = "key=";
	String AMPERSAND_CALLBACK_RECEIVER_REF_ID = "&amp;callback=receiver&refId=";
	String AMPERSAND_PREFIX = "&prefix=";
	String GENERATE_PREVIEW = "generatePreview";
	String GENERATE_PREVIEW_URL = "generatePreviewUrl";
	String TAG_NAME = "tagName";
	String LESSONS = "Lessons";
	String UPDATE_PRIMARY_CONTRIUTOR = "updatedPrimaryContriutor";
	String BOLD_OPEN_STYLE_COLOR = "<b style='color:#5d0e8b'>";
	String BOLD_OPEN_STYLE_COLOR_ROYAL_BLUE = "<b style='color:#0066b3'>";
	String BOLD_TAG_CLOSE = "</b>";
	String YOU = "you";
	String THREAD_ID = "threadId";
	String EEEE_MMM_D_YYYY = "EEEE, MMM. d, yyyy";
	String INVITE_TO_JOIN_LESSON = "InviteToJoinLesson";
	String COMMON_NONE = "none";
	String REQUEST_DETAILS = "requestDetails";
	String REFERENCE_ID_DOC_UUID_AMPERSAND = "ReferenceId=#docUuid&";
	String DATE_ULOADED_TIME_AMPERSAND = "Date=#uploadedTime&";
	String AMPERSAND_CHAPTER_ID_CHAPTER_ID = "&chapterId=#chapterId";
	String AMPERSAND_CHAPTER = "&Chapter=";
	
	
	String TAG_HTML_OPEN_NEWLINE = "<html>\n";
	String TAG_HEAD_TITLE_ERROR_NEWLINE = "<head><title>Error</title></head>\n";
	String TAG_BODY_HEADER_FOUR = "<body><h4 style='color:red'>";
	String TAG_HEADER_FOUR_BODY_HTML = "</h4></body>\n</html>";
	String TAG_HEAD_NEWLINE = "<head>\n";
	String TAG_META_DATA_HTTP_CACHE_CONTROL = "<meta http-equiv=\"cache-control\" content=\"no-store, no-cache, must-revalidate, max-age=0, post-check=0, pre-check=0\" />\n";
	String TAG_META_DATA_HTTP_EQUIV_EXPIRES = "<meta http-equiv=\"expires\" content=\"Mon, 01 Jan 2001 00:00:00 GMT\" />\n";
	String TAG_META_DATA_HTTP_QEUIV_PRAGMA = "<meta http-equiv=\"pragma\" content=\"no-cache\" />\n";
	String TAG_HEAD_END_NEWLINE = "</head>\n";
	String TAG_BODY_OPEN_NEWLINE = "<body>\n";
	String TAG_FORM_OPNE_ACTION = "<form action=\"";
	String TAG_QOUTE_METHOD_GET = "\" method=\"get\">\n";
	String TAG_INPUT_TYPE_HIDDEN = "<input type='hidden' name='";
	String TAG_CLOLSE_NEWLINE = "'/>\n";
	String TAG_FORM_CLOSE_NEWLINE = "</form>\n";
	String TAG_SCRIPT_JAVASCRIPT_SUBMITPAGE_METHOD = "<script type=\"text/javascript\"> function submitPage(){ document.forms[0].submit(); } submitPage(); </script>\n";
	String TAG_BODY_CLOSE_NEWLINE = "</body>\n";
	String TAG_HTML_CLOSE = "</html>";
	String TAG_BOLD_OPEN = "<b>";
	String TAG_DIV_CATEGORY_CONTENT_ROW_FLUID = "<div class=\"category_content\"><div class=\"lessons-list row-fluid\">";
	String TAG_DIV_CLASS_COMMENT_NAME_CLEARFIX = "<div class='comment-name clearfix'><Strong>";
	String TAG_STRONG_CLOSE = "</Strong>";
	String TAG_DIV_CLOSE = "</div>";
	String TAG_PARA_OPEN = "<p>";
	String TAG_PARA_CLOSE = "</p>";
	String TAG_ANCHOR_ONCLICK_DELETE_COMMENT = "</Strong><a id='moreCommentsBtn' class='btn btn-default white pull-right' onclick='deleteComment(";
	String TAG_SPAN_CLASS_ICON_PEN_DIV_PARA_OPEN = ")'><span class='icon-pen trash vertical-align'></span> </a></div><p>";
	
	String TAG_ANCHOR_REF = " <a href='";
	String TAG_FONT_COLOR_BLUE = "'><font color=\"blue\">";
	String TAG_DIV = "<div ";
	String TAG_CLASS_BODY_BODY_TEXT = "class=\"body\">[$BODY_TEXT$]";
	String TAG_FONT_CLOSE_ANCHOR = "</font></a>";
	
	String ACCEPT_USER_TO_GROUP = "acceptUsertoGroup";
	String DECLINE_USER_INVITATION = "declinetUserInvitation";
	String ACCEPT_USER_INVITAION = "acceptUserInvitation";
	String APPROVE = "Approve";	
	String DECLINE_USER_TO_GROUP = "declineUsertoGroup";
	
	String BODY_TEXT_DOLLAR = "[$BODY_TEXT$]";
	String DOLLAR_TITLE = "[$TITLE$]";
	String DOLLAR_CONFIRM = "[$CONFIRM$]";
	String DOLLAR_CONFIRM_URL = "[$CONFIRM_URL$]";
	String DOLLAR_DECLINE = "[$DECLINE$]";
	String DOLLAR_DOLLAR_DECLINE_URL = "[$DECLINE_URL$]";
	
	String CAPITAL_ACCEPT = "Accept";
	String CAPITAL_DECLINE = "Decline";
	String SHOW_DETAILS = "showDetails";
	String JAVASCRIPT_COLON_VOID_ZERO = "javascript:void(0)";
	String TAG_SPAN_DISPLAY_NONE_SHOW_MORE_BUTTON = "<span style='display:none'>ShowMoreButton<span>";
	String TAG_LINE_BREAK = "<br/>";
	String TAG_DIV_CLASS_TITLE_DOLLAR_TITLE = "<div class=\"title\">[$TITLE$]</div><div ";
	String TAG_CLASS_BODY_DOLLAR_BODY_TEXT = "class=\"body\">[$BODY_TEXT$]<a class=\"btn btn-action ";
	String TAG_BTN_SUCCESS_BUTTON_CLICK_HREF_DOLLAR_CONFIRM_DETAIL = "btn-success button-click\" href=\"[$CONFIRM_URL$]\">[$CONFIRM$]</a>";
	String TAG_ANCHOR_CLASS_BTN_ACTION = "<a class=\"btn btn-action ";
	String TAG_BTN_PRIMARY_CLICK_DOLLAR_DECLINE_URL = "btn-primary button-click\" href=\"[$DECLINE_URL$]\">[$DECLINE$]</a>";
	
	String TAG_HEADER_DIV_CLASS_MESSAGE_BODY = "</h4><div class='message-body shadow'>";
	String VALUE_STRING_INSIDE_SINGLE_QUOTE = "' value='";
	String INVITE_TO_JOIN_GROUP = "InviteToJoinGroup";
	String SELECTED_VALUE = "selectedValue";
	String HASH_LAUNCHER_KEY = "#launcher.key";
	String HASH_MODERATOR = "#moderator";
	String HASH_UPLOADED_TIME = "#uploadedTime";
	String HASH_DOC_UUID = "#docUuid";
	String HASH_COURSE_ID = "#courseId";
	String HASH_UPLOADED_BY_NAME = "#uploadedByName";
	String HASH_TRANSCRIBE = "#transcribe";
	String HASH_CHAPTER_ID = "#chapterId";
	String ADMINISTRATOR = "administrator";
	String DATE_AND_TIME = "dateAndTime";
	String GENERAL = "general";
	
	String CAPITAL_T_TRUE = "True";
	String CAPITAL_F_FALSE = "False";
	
	String LAUNCH_ERROR = "launchError";
	
	String CAPITAL_D_DATE = "Date";
	String EXPIRES = "Expires";
	String CACHE_CONTROL = "Cache-Control";
	String MUST_VALIDATE = "must-revalidate";
	String NOT_STORE = "no-store";
	String MAX_AGE_EQUAL_ZERO = "max-age=0";
	String S_MAX_AGE_EQUAL_ZERO = "s-maxage=0";
	String DOUBLE_BACK_SLASH_QUESTION_MARK = "\\?";
	String MANAGE_TYPE = "manageType";
	String MANAGE_BADGES = "manageBadges";
	String USER_ACCEPTANCE_OF_TOU = "userAcceptanceOfTOU";
	String TERMS_OF_USE_JSP = "termsOfUse";
	String PRIVACY_STATEMENT_JSP = "privacyStatement";
	String COMMUNITY_GUIDELINES_JSP = "communityGuidelines";
	String BADGE_ID = "badgeId";
	String BADGE_NAME = "badgeName";
	String EDITABLE_BADGE = "editbadge";
	String ADMIN_DETAILS_JSP = "/WEB-INF/jsp/admin/details.jsp";
	String ADMIN_UPDATE_JSP = "/WEB-INF/jsp/admin/update.jsp";
	String ADMIN_CATEGORIES_JSP = "/WEB-INF/jsp/admin/categories.jsp";
	String ADMIN_TAGS_JSP = "/WEB-INF/jsp/admin/tags.jsp";
	String ADMIN_ADD_DPATE_KEYWORDS_JSP = "/WEB-INF/jsp/admin/addUpdateKeyword.jsp";
	String SITE_HOME_LESSON_REPORT_JSP = "/WEB-INF/jsp/admin/lessonsReport.jsp";
	String ADMIN_TOU_REPORT_JSP = "/WEB-INF/jsp/admin/TOUReport.jsp";
	String AUDIT_DETAILED_REPORT_JSP = "/WEB-INF/jsp/audit/detailedReport.jsp";
	String AUDIT_GENERATE_REPORT_JSP = "/WEB-INF/jsp/audit/generateReport.jsp";
	String USERGROUP_REQUEST_MEMBERS_JSP = "/WEB-INF/jsp/userGroup/requestedMembers.jsp";
	
	String DUPLICATE_BADGE_ID = "DuplicateBadgeId";
	String DELETE_CLAIMED_BADGES = "DeleteClaimedBadges";
	String MANAGE_KEYWORDS = "manageKeywords";
	String KEYWORD_ID = "keywordId";
	String KEYWORD = "keyword";
	String SET_CONTENT_TYPE_APPLICATION_PDF = "application/pdf";
	
	String CUR = "cur";
	String TARGET_POINTS = "targetPoints";
	String FROM_DATE = "fromDate";
	String TO_DATE = "toDate";
	String DETAILS_JSP = "details";
	String ERROR = "error";
	String MOST_RECENT = "mostRecent";
	String TOU_REPORT = "TOUReport";
	String TOU_REPORTS = "TOUReports";
	String MINUS_ONE = "-1";
	String LAST_LOGIN_DATE = "lastLoginDate";
	String MID_NIGHT_TIME = "23:59:59";
	String BEGINING_TIME = "00:00:00";
	String MM_DD_YYYY_HH_mm_SS = "MM/dd/yyyy hh:mm:ss";
	String AGREES_TO_TERMS_OF_USE = "agreedToTermsOfUse";
	String USER_ACCEPTANCE_URL = "userAcceptanceURL";
	String REPORT_TYPE = "reportType";
	String PDF = "pdf";
	String DELTA = "delta";
	String GENERATE_REPORT = "generateReport";
	String GENERATE_REPORT_URL = "generateReportURL";
	String AUDIT_EVENT_ID = "auditEventId";
	String AUDIT_REPORT = "auditReport";
	String UTF_EIGHT = "UTF-8";
	String SEARCH_CONTAINER = "searchContainer";
	String AUDIT_REPORTS = "auditReports";
	String CLOSE_POPUP = "closePopup";
	String IS_FILE_ADDED = "isFileAdded";
	String MSG_ATTACHED_FILE = "msgattachedFile";
	String USER_GROUP = "usergroup";
	String CURRENT_MONTH_STATE = "currentMonthStats";
	String LAST_MONTH_STATE = "lastMonthStats";
	String CONTRIBUTOR_USER_ID = "contributorUserId";
	String USER_LESSONS = "userLessons";
	String USER_REQUEST = "userRequest";
	String USER_CONTRIBUTION_DATA = "userContributionData";
	String CONTRIBUTOR = "contributor";
	String REDIRECT_URL = "redirectUrl";
	String GET_LESSONS = "getLessons";
	String GET_CATEGORIES = "getCategories";
	String GET_TAGS = "getTags";
	String START = "start";
	String END = "end";
	String END_RESULT = "endResult";
	String USER_LESSON_REQUEST = "userLessonsRequest";
	String START_PERIOD = "startPeriod";
	String TOTAL_VALUE = "totalValue";
	String RANK = "rank";
	String CONTRIBUTION_CURRENT_VALUE = "contributionCurrentValue";
	String PARTICIPATION_CURRENT_VALUE = "particpationCurrentValue";
	String CONTRIBUTION_TOTAL_VALUE = "contributionTotalValue";
	String PARTICIPATION_TOTAL_VALUE = "particpationTotalValue";
	String AFTER_CREATE = "afterCreate";
	String LESSON_DETAIL = "lessonDetail";
	String GROUP_ANNOUNCEMENTS = "groupAnnouncements";
	String GROUP_REQUEST = "groupRequest";
	String ANNOUNCEMENT = "announcement";
	String PARENT_MESSAGE_ID = "parentMessageId";
	String ROOT_MESSAGE_ID = "rootMessageId";
	String DELETED = "deleted";
	String MESSAGE_ID = "messageId";
	String USER_NOTE = "userNote";
	String RE_COLON = "RE :";
	String DISCUSSION_DETAIL = "discussionDetail";
	String GROUP_SUB_DISCUSSION_LIST = "groupSubDiscussionList";
	String IS_DISCUSSION_ON_ADMIN = "isDiscussionAdmin";
	String DISCUSSION_RESULTS = "discussionResults";
	String REQUESTED_ID = "requested-id";
	String REQUESTED_MEMBERS = "requestedMembers";
	String USER_GROUP_ID = "usergroupId";
	String GROUP_DATA = "GroupData";
	String GET_GROUPS = "getGroups";
	String PLACE_HOLDER_GROUP_PNG = "placeholder_group.png";
	String ADD_LESSONS = "addLessons";
	String LESSON_IDS_CHECKBOX = "lessonIdsCheckbox";
	String AUTHOR_LESSONS = "authorLessons";
	String USER_GROUP_LESSONS_IDS = "userGroupLessonsIds";
	String CATA_ID = "cataId";
	String REQUESTED_ACCEPTED = "requestAccepted";
	String SUBSCRIBE = "subscribe";
	String UN_REQUESTED = "unrequested";
	String UN_REQUEST = "unrequest";
	String USER_GROUP_HYPER_LINK = "userGroupHyperLink";
	String REQUEST_TO_JOIN = "requestToJoin";
	String REQUEST_JOIN = "requestJoin";
	String SUBS_DATA = "subsData";
	String IS_IMAGE_DELETED = "isImageDeleted";
	String IS_IMAGE_CHANGED = "isImageChanged";
	String GROUP_DESCRIPTION = "groupDescription";
	String GROUP_PRIVACY = "groupPrivacy";
	String USER_CAPITAL_GROUP = "userGroup";
	String GROUP_CAPITAL_LOGO = "groupLogo";
	String KEYWORD_CAPITAL_NAME = "keywordName";
	String CAPITAL_USER_GROUP = "UserGroup";
	String IS_HEADER = "isHeader";
	String GROUP_ACTION_TYPE = "groupActionType";
	String UPDATE_GROUP = "updateGroup";
	String GROUP_DELETED_SUCCESS = "groupDeleteSuccess";
	String REQUEST_DECLINED = "requestDeclined";
	String MEMBER_ID = "memberId";
	String TAKE_VIDEO_URL = "takeTourVideoUrl";
	String SLIDE_ID = "slideId";
	String DESC_POSITION = "descPosition";
	String IMAGE_LINK = "imageLink";
	String SLIDE_IMAGE = "slideImage";
	String SLIDES_JSON_ARRAY = "slidesJSONArray";
	String SLIDE_DESCRIPTION = "slideDescription";
	String SLIDE_IMG = "slideImg";
	String SLIDE_POSITION = "slidePosition";
	String IS_EDIT_SLIDE = "isEditSlide";
	String SLIDE_JSP = "slide";
	String FAIL = "fail";
	String OPTIONS_RADIOS = "optionsRadios";
	String CAPITAL_SLIDE_IMAGE = "SlideImage";
	String SLIDES_IMAGES = "Slides-Images";
	String FILTER_TYPE = "filterType";
	String CREATE_LESSON = "createLesson";
	String SMALL_OPEN = "open";
	String DOCUMENT_PATH_ARR = "documentPath[]";
	String UNPUBLISH_DOC_PATH_ARR = "unpublishDocPath[]";
	String EMBED_MEDIA_PATH_ARR = "embedMediaPath[]";
	String EXISTING_EMBED_MEDIA_PATH_ARR = "existingEmbedMediaPath[]";
	String LESSON_SUCCESS = "lesson_success";
	String UPDATE_LESSON = "updatedLesson";
	String WEB = "web";
	String SAVE_LESSON = "saveLesson";
	String LESSON_UNPUBLISHED = "lesson_unPublished";
	String SECONDARY_AUTHOR_IDS_CHECK_BOX = "secondaryAuthorIdsCheckbox";
	String CREATOR = "creator";
	String CATEGORY = "category";
	String SUB_CATEGORY = "subcategory";
	String LIFERAY_SITE_LESSON_STATUS_PERIOD = PortletProps.get("liferay.site.lesson.status.dot");
	String PRIVACY_CHECK = "privacyCheck";
	String ADMIN = "admin";
	String COMPANY_ID = "companyId";
	String LESSON_CONTRIBUTOR = "lessonContributor";
	String UNPUBLISH_RESOURCE_ID_ARR = "unpublishResourceId[]";
	String UNPUBLISHED_DOC_IDS = "unpublishDocIds[]";
	String AUTHOR = "author";
	String FILE = "file";
	String PUBLISH = "publish";
	String THUMBNAIL_JSP = "thumbnail";
	String RESOURCE_ID_ARR = "resourceId[]";
	String COLLECTION_ID_ARR = "collectionId[]";
	String DOCUMENT_NAME_ARR = "documentName[]";
	String DOCUMENT_TITLE_ARR = "documentTitle[]";
	String DOCUMENT_DESC_ARR = "documentDesc[]";
	String EMBED_MEDIA_TITLE_ARR = "embedMediaTitle[]";
	String EMBED_MEDIA_DESC_ARR = "embedMediaDesc[]";
	String EXISTING_EMBED_MEDIA_TITLE_ARR = "existingEmbedMediaTitle[]";
	String EXISTING_EMBED_MEDIA_DESC_ARR = "existingEmbedMediaDesc[]";
	String EXISTING_RESOURCE_ID_ARR = "existingResourceId[]";
	String EXISTING_DOC_PATH_ARR = "existingDocPath[]";
	String EXISTING_DOC_NAME = "existingDocName[]";
	String AMPERSAND_UUID_EQUAL = "&uuid=";
	String AUTO_TRANSCRIPT_ARR = "autoTranscript[]";
	String YYYY_MM_DD_HH_mm_SS = "yyyy-MM-dd HH:mm:ss";
	String V_EQUAL = "v=";
	String ADD_LESSON = "addedLesson";
	String TAGS_SIZE = "tagsSize";
	String ADD_TO_MY_FAVOURITE = "addToMyFavourite";
	String MARKED_AS = "markedAs";
	String MARKED_BY_USER = "markedByUser";
	String CHECK_MARKED_AS = "checkMarkedAs";
	String LESSON_SUB_DISCUSSION_LIST = "lessonSubDiscussionList";
	String LESSON_BY_CATEGORY_AND_TAGS = "lessonsByCategoryAndTags";
	String LESSON_BY_USER_INTEREST = "lessonsByUserInterest";
	String LESSON_VIEWED_AUTHORS_MAP = "lessonViewedAuthorsMap";
	String DOCUMENT_FILE_LIST = "documentFileList";
	String DELETE_LESSON = "deleteLesson";
	String SELECTED_PLAY_IDS = "selectedPlayIds";
	String FOLLOW_USER = "followUser";
	String UN_FOLLOW_USER = "unFollowUser";
	String NOT_FOLLOWING = "NOTFOLLOWING";
	String USER_LESSON_MAP = "userLessonsMap";
	String COUNTS = "counts";
	String UPLOAD_BY_ID = "uploadedById";
	String STATUS = "status";
	String CURRENT_AUTHOR = "currentAuthor";
	String LESSON_STATUS = "lessonStatus";
	String CHECKED_LESSON = "checkedLesson";
	String ADD_FEATURED_LESSONS = "addFeaturedLessons";
	String AMPERSAND_KEY_EQUAL = "&key=";
	String RESOURCE_URL = "resourceUrl";
	String PREVIEW_DOCUMENTS = "previewDocuments";
	String PRIMARY_KEY_USER_ID = "primaryKey.userId";
	String PRIMARY_KEY_LESSON_ID = "primaryKey.lessonId";
	String MARKED_AS_CONTENT = "markedContent";
	String BROWSE = "browse";
	String IN_APPROPRIATE = "inappropriate";
	String REASON = "reason";
	String CAPITAL_LESSON = "Lesson";
	String MAKE_LESSON_AS_FEATURED = "makeLessonAsFeatured";
	String UNCHECKED_LESSON = "unCheckedLesson";
	String FEATURED = "featured";
	String DDMMYYYY_HHmmSS = "ddMMyyyy_hhmmss";
	String IMAGES_SLASH_TEMP_SLASH = "images/temp/";
	String USER_GROUPS_CHECK_BOX = "usergroupsCheckbox";
	String TAG_CLOSE_CODE= "</code>";
	String LIST_OF_USERS = "listOfUsers";
	String SHOW_FOLLOWING = "showFollowing";
	String FOLLOW_LEFT_SPACE = "followLeftSpace";
	String DEFAULT_MAX_COMMENTS = "defaultMaxComments";
	String CAPITAL_ADMINISTRATOR = "Administrator";
	String THREE_SPACES= "   ";
	String SIZE_OF_INSERT_COMMENT_COLON = "sizeofinsertComment:";
	String EMAIL_LESSON_ID = "emailLessonId";
	String PUBLIC_URL = "publicUrl";
	String PORTLET_PROP_AT_RATE_SITE_EXTENSION = PortletProps.get("at.rate.site.extension");
	String CROP_REGION_X = "cropRegion_x";
	String CROP_REGION_Y = "cropRegion_y";
	String CROP_REGION_WIDTH = "cropRegion_width";
	String CROP_REGION_HEIGHT = "cropRegion_height";
	String DUMMY = "dummy";
	String ORIGINAL_WIDTH = "original_width";
	String ORIGINAL_HEIGHT = "original_height";
	String USER_COMMENTS = "userComments";
	String NUMBER_OF_COMMENTS_ON_LOAD = "numberOfCommentsOnload";
	String NUMBER_OF_COMMENTS_ON_CLICK = "numberOfCommentsOnclick";
	String LESSON_PUBLISHED_COUNT = "lessonPublishedCount";
	String COMMENTS_ADDED_COUNT = "commentsAddedCount";
	String REQUEST_ACCEPTED_COUNT = "requestAcceptedCount";
	String ACCEPTED_BY = "acceptedBy";
	String LAST_ACTIVITY = "lastActivity";
	String DD_MM_YYYY = "dd/MM/yyyy";
	String ARCHIVE_TYPE = "archiveType";
	String CONTRIBUTION_POINTS = "countributionPoints";
	String CONTRIBUTION_TOTAL_POINTS = "countributionTotalPoints";
	String PARTICIPATION_TOTAL_POINTS = "participationTotalPoints";
	String PARTICIPATION_POINTS = "participationPoints";
	String CAPITAL_RANK = "Rank";
	String CAT_ID = "catId";
	String MYSTUFF_SCRLL_LOAD_JSP = "/WEB-INF/jsp/mystuff/scrollLoad.jsp";
	String COUNT = "count";
	String MY_FOLLOWER_LIST = "myFollowersList";
	String ACTIVITIES = "activities";
	String ARCHIVED_LESSON_PARAM = "archeivedLessonParam";
	String REQUESTED_LESSON_ACCEPTED = "requestLessonAccepted";
	String ANNOUNCEMENT_ENTRIES = "announcementEntries";
	String KEYWORDS_REQUEST_STATUS = "keywordsRequestStatus";
	String KEYWORDS_REQUEST = "keywordsRequest";
	String KEYWORDS_REQUEST_RESPONSE = "keywordRequestResponse";
	String ARCHIVED_LESSONS = "archivedLessons";
	String ALL_USER_BADGES = "allUserBadges";
	String BASGES_LIST = "basgesList";
	String HTTPS = "https";
	String PREVIEW_URL = "preview_url";
	String OPEN_CURLY_BRACE_DOUBLE_QUOTE_PID = "{\"pid\":\"";
	String BACK_SLASH_CLOSE_CURLY_BRACE = "\"}";
	String APPLICATION_SLASH_JSON = "application/json";
	String POST = "POST";
	String API_SLASH_ISSUE_URL = "/api/issue/url";
	String BADGE_URL = "badgeUrl";
	String MY_FOLLOWING_USER_LIST = "myFollowingUserList";
	String KEYWORDS_COLLABORATIONS = "keywordsCollaborations";
	String PERIOD_TEXT = ".txt";
	String LOCATION = "Location";
	String LAUNCHER_KEY = "LauncherKey";
	String REFERENCE_ID = "ReferenceId";
	String WITH_TRANSCRIPT = "WithTranscript";
	String NEW_USER_NOTIFICATIONS_COUNT = "newUserNotificationsCount";
	String TIME_STAMP = "timestamp";
	String NEWLY_PUBLISHED_LIST = "newlyPublishedList";
	String ARCHIVED = "archived";
	String KNOWLEDGE_COMMONS = "Knowledge Commons";
	String EMAIL_DIGEST_FROM_KNOWLEDGE_COMMONS = "Email digest from Knowledge Commons";
	String NOTIFICATION_COUNT = "notificationCount";
	String REQUEST_ACCEPT_COUNT = "requestAcceptCount";
	String HOST = "host";
	String E_MMM_D_Y = "E,MMM. d, y";
	String UN_SUBSCRIBE = "unsubscribe";
	String BTN = "btn";
	String LEAVE = "Leave";
	String BTN_BTN_PRIMARY = "btn btn-primary";
	String UNREQUEST = "Unrequest";
	String BTN_BTN_INFO = "btn btn-info";
	String JOIN = "Join";
	String BTN_BTN_WARNING = "btn btn-warning";
	String YEARS_AGO = "year(s) ago";
	String DAYS_AGO = "day(s) ago";
	String HRS_AGO = "hr(s) ago";
	String MINS_AGO = "min(s) ago";
	String SECS_AGO = "sec(s) ago";
	String REQUEST_TO_JOIN_STRING = "Request to join";
	String SLASH_DEFAULT_JPG = "/default.jpg";
	String SITTE_UTIL_CLASS = "NyuUtil.class";
	String FILE_COLON_SLASH = "file:/";
	String JAR_COLON = "jar:";
	String LIB = "lib";
	String CLASSES_STRING = "classes";
	String WEB_INF_STRING = "WEB-INF";
	String CHANGE_LOG = "changeLog";
	String FAILED = "failed";
	String CREATE_LESSON_STRING = "Create Lesson";
	String UPDATE_LESSON_STRING = "Update Lesson";
	String X_FORWARD_FOR = "X-FORWARDED-FOR";
	String LESSON_AND_REQUESTS = "lessonAndRequests";
	String DOUBLE_BACK_SLASH_DOT = "\\.";
	String AUTH_ACTIVITY_FEED_MAP = "authActivityFeedMap";
	String USER_ACCEPTANCE_CONTAINER = "userAcceptanceContainer";
	String CATEGORY_NAME = "categoryName";
	String YES_NO_MAYBE = "Yes,No,Maybe";
	String BRACKET_OPEN_BACK_SLASH_W_SLASH_S_SLASH_HYPHEN_CLOSE = "[^\\w\\s\\-_]";
	String FROM_MY_STUFF = "fromMyStuff";
	String FROM_VIEW_LESSON = "fromViewLesson";
	String RELATED_ID = "related";
	String USER_NAME = "username";
	String STYLE_COLOR = "style_color";
	String HREF = "href";
	String ROLE = "role";
	String COUNTER = "counter";
	String DISPLAY_NAME = "displayname";
	String D_F_ONE = "DF1-";
	String USER = "User";
	String INFO = "info";
	String CAPITAL_CATEGORY = "Category";
	String SPAN_CLASS_HIGHLIGHT = " <span class='highlight'>";
	String TAG_SPAN_CLOSE = "</span>";
	String TAG_NON_BREAK_EMPTY_SPACE_SPAN_ARIA_HIDDEN_CLASS_ICON_COMMENT = "&nbsp;&nbsp;&nbsp;&nbsp;<span aria-hidden='true' class='icon-comment'></span> ";
	String TAG_NON_BREAK_EMPTY_SPACE_SPAN_ARIA_HIDDEN_CLASS_ICON_EYE_OPEN = "&nbsp;&nbsp;&nbsp;&nbsp;<span aria-hidden='true' class='icon-eye-open'></span> ";
	String TAG_SPACE_SPAN_ARIA_HIDDEN_CLASS_ICON_THUBS_UP = "<span aria-hidden='true' class='icon-thumbs-up'></span> ";
	String TAG_SPACE_SPAN_CLASS_HIGHLIGHT = "<span class='highlight'> ";
	String TAG_SPAN_DOT_BREAK_LINE = "</span>. <br/>";
	String STRING_COSNTANT_SEVEN = "7";
	String STRING_COSNTANT_TEN = "10";
	String STRING_COSNTANT_SIXTEEN = "16";
	String STRING_COSNTANT_FOUR = "4";
	String VIDEO_URL = "videoUrl";
	String TAG_STRONG_OPEN = "<strong>";
	String DECLINE_LESSON_INVITATION = "declineLessonInvitation";
	String REDIRECT = "redirect";
	String ACCEPT_LESSON_INVITATION = "acceptLessonInvitation";
	String ACCEPT = "accept";
	String DECLINE = "decline";
	String YOUR_CUSTOM_ENTITY_ID = "yourCustomEntityId";
	String CATEGORY_VOCABULARY = "NY-YOU";

	String NEW_SHOW_REQUEST = "new Request";
	String SHOW_REQUEST_PAGE = "showRequestPage";
	String SHOW_POP_OVER = "showPopOver";
	String EXPLICIT_PREVIEW_FORMATS = PortletProps.get("explicit.preview.formats.to.play.in.engage");
	boolean ENABLE_OFFICE_PREVIEW_IN_ENGAGE = GetterUtil.getBoolean(PortletProps.get("enable.office.preview.in.engage"));
	
	String GROUP_PRIVACY_PUBLIC = "public";
	String GROUP_PRIVACY_COLLABORATOR = "collaborator";
	String GROUP_PRIVACY_PRIVATE = "private";
	String SINGLE_SELECT = "singleSelect";
		
	boolean IS_FOR_VENDOR = GetterUtil.getBoolean(PropsUtil.get("require.nyu.related.stuff")); 
	boolean IS_BADGES_REQUIRE = GetterUtil.getBoolean(PropsUtil.get("require.basno.badges"));
	boolean IS_SURVEY_REQUIRE = GetterUtil.getBoolean(PropsUtil.get("require.external.surveys"));

	String DOCUMENT_STATUS ="document_status";
	String DOCUMENT_STATUS_ARCHIVE = "archive";
	String DOCUMENT_STATUS_S3 = "s3";
	String DOCUMENT_STATUS_CDN = "cdn";
	String DOCUMENT_STATUS_COMPLETED = "completed";
	String NO_ID="NO_ID";
	String SUCCESS = "SUCCESS";
	String DOCUMENT_STATUS_CONTAINER = "documentStatusContainer";
	String EMAILDIGEST = "emailDigest";
	String EMAIL_DIGEST_ATTRIBUTE = "is-email-digest-required";
	String EMAIL_DIGEST_JSP = "emailDigest";
	String EMAILDIGESTPROCESS = "emailDigestProcess";
	
	String SIGNUP_VIEW_JSP = "signup";
}
